// Le Méandre — contenu et données du site (français + anglais).
// Chargé en <script> classique avant que index.html n'évalue son
// Component : tout ici est posé sur `window` pour être lu depuis
// Component.renderVals(). C'est le fichier à modifier pour changer un texte,
// un plat de la carte, un gîte ou une traduction — pas besoin de toucher au
// gabarit HTML dans index.html pour ça.

// ── Easing (fonctions de courbe d'animation), utilisées par l'écran de
//    chargement dans Component._loaderVals(). ──
window.MeandreEasing = {
  outCubic: (t) => 1 - Math.pow(1 - t, 3),
  inOutSine: (t) => -(Math.cos(Math.PI * t) - 1) / 2,
  inOutCubic: (t) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2),
  clamp: (v, a, b) => Math.min(b, Math.max(a, v)),
};

// ── Tracé vectoriel du logo pour l'écran de chargement ──
// 3 volutes qui se dessinent comme une branche qui pousse.
// Chaque entrée : [d, largeur, début, durée] sur la progression de la scène "Tourbillon".
window.MEANDRE_LOADER_STROKES = [
  ['M 418 452 C 255 494, 76 432, 54 286 C 33 152, 138 42, 260 47 C 332 51, 346 112, 299 135 C 268 150, 243 128, 252 104', 9, 0.00, 0.42],
  ['M 100 248 C 118 358, 232 414, 342 363 C 400 336, 418 292, 398 268', 8, 0.22, 0.30],
  ['M 366 260 C 462 296, 492 396, 434 456 C 419 470, 400 466, 404 450', 8, 0.40, 0.28],
];
// feuilles : [x, y, rotation, échelle, début] — chacune se dessine puis se remplit
window.MEANDRE_LOADER_LEAVES = [
  [42, 82, -32, 1.15, 0.50], [102, 58, -4, 0.8, 0.56],
  [398, 88, 24, 1.0, 0.60], [448, 162, 62, 0.9, 0.66],
  [268, 332, 168, 1.0, 0.63], [150, 322, 198, 0.8, 0.70],
];

// ── Textes de l'interface (nav, en-têtes, appels à l'action, légendes) ──
window.MEANDRE_UI = {
  fr: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'À EMPORTER', navGites: 'LE GÎTE', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'RECRUTEMENT', footerScene: 'SCÈNE & ART',
    heroTagline: "Restaurant, gîte et spa dans un ancien relais chargé d'histoire, au cœur de la Vallée de la Course.",
    cardRestTitle: 'Le Restaurant', cardRestDesc: 'Une cuisine raffinée entre terre et mer, au fil des saisons.',
    cardGitesTitle: 'Le Gîte', cardGitesDesc: "Quatre chambres indépendantes, à réserver séparément, au sein d'une même maison.",
    cardSpaTitle: 'Le Spa', cardSpaDesc: 'Une piscine intérieure, dans une quiétude absolue.',
    discover: 'DÉCOUVRIR →',
    artEyebrow: 'BIENVENUE AU MÉANDRE', artTitle1: "Un lieu chargé d'histoire, au cœur de", artTitle2: 'la Vallée de la Course.',
    artParagraph: "Ancien relais dédié à l'accueil des voyageurs, la maison a connu plusieurs vies avant d'écrire aujourd'hui un nouveau chapitre sous le nom du Méandre. Restaurant, gîte et spa s'y conjuguent dans un esprit chaleureux et raffiné — une nouvelle histoire qui s'écrit au fil de la Course.",
    ctaContact: 'NOUS CONTACTER',
    eventEyebrow: 'SÉMINAIRES · MARIAGES · RÉCEPTIONS', eventTitle: "L'Événementiel",
    eventTagline: "Le relais se prête aussi à vos temps forts : mariages champêtres, séminaires d'entreprise, réceptions privées ou repas de famille.",
    eventParagraph: "Salle de réception, terrasse, jardin et salon privé, cuisine du restaurant et gîte pour l'hébergement des invités : nous composons chaque événement sur mesure, du cocktail au jardin au dîner dans notre salon privé.",
    eventCta: 'DEMANDER UN DEVIS',
    restEyebrow: 'CUISINE ENTRE TERRE ET MER', restTitle: 'Le Restaurant', restTagline: 'Une cuisine raffinée, entre terre et mer, au fil des saisons.',
    menuEyebrow: 'LA CARTE', menuTitle: 'Le Menu',
    menuTerroirTitle: 'Menu Terroir', menuTerroirSub: 'Entrée · Plat · Dessert',
    menuEstreeTitle: 'Menu Signature', menuEstreeSub: 'Dégustation en six temps, accords mets & vins',
    galleryEyebrow: 'EN IMAGES', galleryTitle: "La table, la salle, l'ambiance",
    hoursEyebrow: 'HORAIRES', hoursText: 'Du mercredi au dimanche', hoursLunch: 'Déjeuner · 12h00 – 13h30', hoursDinner: 'Dîner · 19h30 – 21h30', hoursClosed: 'Fermé lundi et mardi',
    cuisineEyebrow: 'LA CUISINE', cuisineText: 'Raffinée · Terre et Mer', cuisineText2: 'Produits de la mer et producteurs locaux', cuisineText3: 'Carte renouvelée à chaque saison',
    resaEyebrow: 'RÉSERVATION', resaText: 'Par téléphone uniquement',
    aemporterEyebrow: 'À EMPORTER', aemporterTitle: 'La Table à Emporter', aemporterTagline: 'La cuisine du restaurant, à savourer chez vous.',
    aemporterParagraph: 'Plats mijotés, entrées et desserts préparés par notre cuisine, à récupérer sur place. La carte change selon la saison et les arrivages — appelez-nous pour connaître les plats du jour.',
    aemporterHoursText: 'Retrait du mercredi au dimanche', aemporterHoursLunch: '12h00 – 13h30', aemporterHoursDinner: '19h00 – 20h30',
    aemporterOrderEyebrow: 'COMMANDE', aemporterOrderText: 'Par téléphone, la veille de préférence', aemporterCta: 'APPELER POUR COMMANDER',
    gitesEyebrow: 'SÉJOURNER AU RELAIS', gitesTitle: 'Le Gîte',
    gitesTagline: 'Une maison restaurée avec soin, à deux pas du restaurant. Quatre chambres indépendantes, à réserver séparément, chacune avec son caractère.',
    gitesDetail1: 'Détail 1', gitesDetail2: 'Détail 2', gitesDetail3: 'Détail 3',
    gitesCtaTitle: 'Envie de séjourner au relais ?', gitesCtaText: 'Chaque chambre se réserve indépendamment, par téléphone ou par écrit. Nous composerons votre séjour avec vous.',
    spaEyebrow: 'SILENCE · CALME · EAU', spaTitle: 'Le Spa', spaTagline: 'Un lieu clos, feutré, réservé aux hôtes du relais.',
    practiceEyebrow: 'EN PRATIQUE', practiceTitle: 'Accès au spa',
    practice1Title: 'Ouvert tous les jours', practice1Text: '10h00 – 20h00, sur créneaux privatisés',
    practice2Title: 'Réservé aux hôtes', practice2Text: 'Inclus pour les séjours en gîte, sur demande au restaurant',
    practice3Title: 'Linge fourni', practice3Text: 'Peignoirs, serviettes et chaussons à disposition',
    ctaBookSlot: 'RÉSERVER UN CRÉNEAU',
    contactEyebrow: 'CONTACT', contactTitle1: 'Écrivez-nous,', contactTitle2: 'ou passez nous voir.',
    addressLabel: 'ADRESSE', phoneLabel: 'TÉLÉPHONE', emailLabel: 'EMAIL',
    contactHours: 'Accueil du lundi au dimanche, 9h – 19h.', contactHours2: 'Restaurant, gîte et spa : toute demande se fait par téléphone ou email — nous répondons sous 24h.',
    formNameLabel: 'NOM', formFirstNameLabel: 'PRÉNOM', formEmailLabel: 'EMAIL', formMessageLabel: 'MESSAGE',
    formNamePh: 'Votre nom', formFirstNamePh: 'Votre prénom', formEmailPh: 'vous@exemple.com', formMessagePh: 'Votre message…',
    formSendBtn: 'ENVOYER LE MESSAGE', formNote: "En cliquant sur envoyer, votre messagerie s'ouvrira avec ce message pré-rempli.",
    recruitEyebrow: 'REJOIGNEZ-NOUS', recruitTitle: 'Recrutement', recruitTagline: 'Le Méandre grandit avec les personnes qui y travaillent.',
    recruitParagraph: "Nous recrutons régulièrement en cuisine, en salle et pour l'entretien du relais et du gîte. Aucun poste ouvert ne vous correspond aujourd'hui ? Envoyez-nous une candidature spontanée : nous gardons chaque CV et reprenons contact dès qu'un poste s'ouvre.",
    recruitCta: 'ENVOYER MA CANDIDATURE', recruitEmailNote: 'CV et lettre de motivation à :',
    sceneEyebrow: 'SCÈNE & ART', sceneTitle: 'Le Méandre ouvre sa scène', sceneTagline: 'Vous êtes artiste ?',
    sceneParagraph: 'Vous êtes musicien, peintre, photographe, humoriste ou artiste du spectacle vivant ? Vous souhaitez exposer, vous produire ou imaginer un projet avec nous ? Nous sommes toujours à la recherche de nouveaux univers et de nouvelles sensibilités à faire découvrir à nos hôtes.',
    sceneFormIntro: 'Proposez votre univers', sceneCta: 'JE PROPOSE MON PROJET',
    sceneDisciplineLabel: 'DISCIPLINE', sceneDisciplinePh: 'Musique, peinture, photographie, spectacle vivant…',
    sceneProjectLabel: 'VOTRE PROJET', sceneProjectPh: 'Décrivez votre univers, votre projet, vos disponibilités…',
    sceneFormNote: "En cliquant sur envoyer, votre messagerie s'ouvrira avec ce message pré-rempli.",
    sinceWord: 'DEPUIS',
    phHero: 'Photo du relais — vue extérieure, grand format', phAccRest: 'Plat signature', phAccGites: "Intérieur du gîte", phAccSpa: 'Piscine intérieure / spa',
    phRestHero: 'Salle du restaurant ou plat — bandeau large', phSpaHero: 'Piscine intérieure — grand format immersif', phContact: "Photo — allée, portail ou plan d'accès",
    phAEmporter: "Affiche de l'offre à emporter du moment — format portrait"
  },
  en: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'TAKEAWAY', navGites: 'THE COTTAGE', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'CAREERS', footerScene: 'STAGE & ART',
    heroTagline: 'Restaurant, cottage and spa in a former coaching inn steeped in history, at the heart of the Course Valley.',
    cardRestTitle: 'The Restaurant', cardRestDesc: 'Refined, seasonal dining between land and sea.',
    cardGitesTitle: 'The Cottage', cardGitesDesc: 'Four independent rooms, bookable separately, within the same house.',
    cardSpaTitle: 'The Spa', cardSpaDesc: 'An indoor pool, in absolute quiet.',
    discover: 'DISCOVER →',
    artEyebrow: 'WELCOME TO LE MÉANDRE', artTitle1: 'A place steeped in history, at the heart of', artTitle2: 'the Course Valley.',
    artParagraph: "A former coaching inn dedicated to welcoming travellers, the house has lived several lives before writing, today, a new chapter under the name Le Méandre. Restaurant, cottage and spa come together here in a warm and refined spirit — a new story unfolding along the Course.",
    ctaContact: 'CONTACT US',
    eventEyebrow: 'SEMINARS · WEDDINGS · RECEPTIONS', eventTitle: 'Events',
    eventTagline: 'The inn also lends itself to your milestone moments: countryside weddings, corporate seminars, private receptions or family gatherings.',
    eventParagraph: "Reception room, terrace, garden and private lounge, our restaurant's kitchen and cottage for guest accommodation: we tailor every event, from a cocktail in the garden to dinner in our private lounge.",
    eventCta: 'REQUEST A QUOTE',
    restEyebrow: 'BETWEEN LAND AND SEA', restTitle: 'The Restaurant', restTagline: 'A refined cuisine, between land and sea, through the seasons.',
    menuEyebrow: 'THE MENU', menuTitle: 'The Menu',
    menuTerroirTitle: 'Terroir Menu', menuTerroirSub: 'Starter · Main · Dessert',
    menuEstreeTitle: 'Signature Menu', menuEstreeSub: 'Six-course tasting menu, wine pairings',
    galleryEyebrow: 'GALLERY', galleryTitle: 'The table, the room, the atmosphere',
    hoursEyebrow: 'HOURS', hoursText: 'Wednesday to Sunday', hoursLunch: 'Lunch · 12:00 – 1:30 PM', hoursDinner: 'Dinner · 7:30 – 9:30 PM', hoursClosed: 'Closed Monday and Tuesday',
    cuisineEyebrow: 'THE KITCHEN', cuisineText: 'Refined · Land and Sea', cuisineText2: 'Seafood and local producers', cuisineText3: 'Menu refreshed every season',
    resaEyebrow: 'RESERVATIONS', resaText: 'By phone only',
    aemporterEyebrow: 'TAKEAWAY', aemporterTitle: 'Takeaway', aemporterTagline: "The restaurant's cooking, to enjoy at home.",
    aemporterParagraph: 'Slow-cooked dishes, starters and desserts prepared by our kitchen, ready for pickup. The menu changes with the season and the market — call us to hear the dishes of the day.',
    aemporterHoursText: 'Pickup Wednesday to Sunday', aemporterHoursLunch: '12:00 – 1:30 PM', aemporterHoursDinner: '7:00 – 8:30 PM',
    aemporterOrderEyebrow: 'ORDERING', aemporterOrderText: 'By phone, ideally the day before', aemporterCta: 'CALL TO ORDER',
    gitesEyebrow: 'STAY AT THE INN', gitesTitle: 'The Cottage',
    gitesTagline: "A carefully restored house, just steps from the restaurant. Four independent rooms, each bookable separately, each with its own character.",
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Fancy a stay at the inn?', gitesCtaText: "Each room is booked independently, by phone or in writing. We'll put together your stay with you.",
    spaEyebrow: 'SILENCE · CALM · WATER', spaTitle: 'The Spa', spaTagline: 'A hushed, enclosed retreat reserved for the inn\'s guests.',
    practiceEyebrow: 'GOOD TO KNOW', practiceTitle: 'Spa access',
    practice1Title: 'Open every day', practice1Text: '10:00 AM – 8:00 PM, in private slots',
    practice2Title: 'Reserved for guests', practice2Text: 'Included with cottage stays, on request at the restaurant',
    practice3Title: 'Linens provided', practice3Text: 'Robes, towels and slippers provided',
    ctaBookSlot: 'BOOK A SLOT',
    contactEyebrow: 'CONTACT', contactTitle1: 'Write to us,', contactTitle2: 'or come see us.',
    addressLabel: 'ADDRESS', phoneLabel: 'PHONE', emailLabel: 'EMAIL',
    contactHours: 'Open Monday to Sunday, 9 AM – 7 PM.', contactHours2: 'Restaurant, cottage and spa: all requests by phone or email — we reply within 24h.',
    formNameLabel: 'LAST NAME', formFirstNameLabel: 'FIRST NAME', formEmailLabel: 'EMAIL', formMessageLabel: 'MESSAGE',
    formNamePh: 'Your last name', formFirstNamePh: 'Your first name', formEmailPh: 'you@example.com', formMessagePh: 'Your message…',
    formSendBtn: 'SEND MESSAGE', formNote: 'Clicking send will open your mail app with this message pre-filled.',
    recruitEyebrow: 'JOIN US', recruitTitle: 'Careers', recruitTagline: 'Le Méandre grows with the people who work here.',
    recruitParagraph: 'We regularly hire in the kitchen, the dining room, and for the upkeep of the inn and cottage. Nothing open that matches you today? Send us a spontaneous application: we keep every CV on file and get back in touch as soon as a position opens.',
    recruitCta: 'SEND MY APPLICATION', recruitEmailNote: 'CV and cover letter to:',
    sceneEyebrow: 'STAGE & ART', sceneTitle: 'Le Méandre opens its stage', sceneTagline: 'Are you an artist?',
    sceneParagraph: 'Are you a musician, painter, photographer, comedian or performing artist? Would you like to exhibit, perform, or imagine a project with us? We are always looking for new worlds and new sensibilities to introduce to our guests.',
    sceneFormIntro: 'Propose your world', sceneCta: 'PROPOSE MY PROJECT',
    sceneDisciplineLabel: 'DISCIPLINE', sceneDisciplinePh: 'Music, painting, photography, live performance…',
    sceneProjectLabel: 'YOUR PROJECT', sceneProjectPh: 'Describe your world, your project, your availability…',
    sceneFormNote: 'Clicking send will open your mail app with this message pre-filled.',
    sinceWord: 'SINCE',
    phHero: 'Inn photo — exterior view, large format', phAccRest: 'Signature dish', phAccGites: 'Cottage interior', phAccSpa: 'Indoor pool / spa',
    phRestHero: 'Dining room or dish — wide banner', phSpaHero: 'Indoor pool — large immersive format', phContact: 'Photo — driveway, gate or access map',
    phAEmporter: "Current takeaway offer poster — portrait format"
  },
  de: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'ZUM MITNEHMEN', navGites: 'DAS GÎTE', navSpa: 'SPA', navContact: 'KONTAKT',
    footerRecrutement: 'KARRIERE', footerScene: 'BÜHNE & KUNST',
    heroTagline: 'Restaurant, Gîte und Spa in einer alten, geschichtsträchtigen Poststation im Herzen des Course-Tals.',
    cardRestTitle: 'Das Restaurant', cardRestDesc: 'Eine raffinierte, saisonale Küche zwischen Land und Meer.',
    cardGitesTitle: 'Das Gîte', cardGitesDesc: 'Vier unabhängige Zimmer, einzeln buchbar, im selben Haus.',
    cardSpaTitle: 'Der Spa', cardSpaDesc: 'Ein Innenpool, in vollkommener Ruhe.',
    discover: 'ENTDECKEN →',
    artEyebrow: 'WILLKOMMEN IM MÉANDRE', artTitle1: 'Ein geschichtsträchtiger Ort im Herzen', artTitle2: 'des Course-Tals.',
    artParagraph: 'Als ehemalige Poststation für Reisende hat das Haus mehrere Leben durchlebt, bevor es heute unter dem Namen Le Méandre ein neues Kapitel aufschlägt. Restaurant, Gîte und Spa vereinen sich hier in einem herzlichen und raffinierten Geist — eine neue Geschichte, die sich entlang der Course schreibt.',
    ctaContact: 'KONTAKTIEREN SIE UNS',
    eventEyebrow: 'SEMINARE · HOCHZEITEN · EMPFÄNGE', eventTitle: 'Veranstaltungen',
    eventTagline: 'Der Gasthof eignet sich auch für Ihre besonderen Momente: Landhochzeiten, Firmenseminare, private Empfänge oder Familienfeiern.',
    eventParagraph: 'Empfangssaal, Terrasse, Garten und privater Salon, die Küche unseres Restaurants und das Gîte für die Unterbringung der Gäste: Wir gestalten jede Veranstaltung individuell, vom Cocktailempfang im Garten bis zum Dinner in unserem privaten Salon.',
    eventCta: 'ANGEBOT ANFORDERN',
    restEyebrow: 'ZWISCHEN LAND UND MEER', restTitle: 'Das Restaurant', restTagline: 'Eine raffinierte Küche, zwischen Land und Meer, im Wandel der Jahreszeiten.',
    menuEyebrow: 'DIE KARTE', menuTitle: 'Die Speisekarte',
    menuTerroirTitle: 'Menü Terroir', menuTerroirSub: 'Vorspeise · Hauptgang · Dessert',
    menuEstreeTitle: 'Signature-Menü', menuEstreeSub: 'Sechsgängiges Degustationsmenü mit Weinbegleitung',
    galleryEyebrow: 'BILDER', galleryTitle: 'Die Tafel, der Saal, die Atmosphäre',
    hoursEyebrow: 'ÖFFNUNGSZEITEN', hoursText: 'Mittwoch bis Sonntag', hoursLunch: 'Mittagessen · 12:00 – 13:30 Uhr', hoursDinner: 'Abendessen · 19:30 – 21:30 Uhr', hoursClosed: 'Montag und Dienstag geschlossen',
    cuisineEyebrow: 'DIE KÜCHE', cuisineText: 'Raffiniert · Land und Meer', cuisineText2: 'Meeresfrüchte und lokale Erzeuger', cuisineText3: 'Karte wechselt jede Saison',
    resaEyebrow: 'RESERVIERUNG', resaText: 'Nur telefonisch',
    aemporterEyebrow: 'ZUM MITNEHMEN', aemporterTitle: 'Gerichte zum Mitnehmen', aemporterTagline: 'Die Küche des Restaurants, zu Hause genießen.',
    aemporterParagraph: 'Geschmorte Gerichte, Vorspeisen und Desserts, zubereitet von unserer Küche und zur Abholung bereit. Die Karte ändert sich je nach Saison und Angebot — rufen Sie uns an, um die Tagesgerichte zu erfahren.',
    aemporterHoursText: 'Abholung Mittwoch bis Sonntag', aemporterHoursLunch: '12:00 – 13:30 Uhr', aemporterHoursDinner: '19:00 – 20:30 Uhr',
    aemporterOrderEyebrow: 'BESTELLUNG', aemporterOrderText: 'Telefonisch, idealerweise am Vortag', aemporterCta: 'TELEFONISCH BESTELLEN',
    gitesEyebrow: 'AUFENTHALT IM GASTHOF', gitesTitle: 'Das Gîte',
    gitesTagline: 'Ein sorgfältig restauriertes Haus, nur wenige Schritte vom Restaurant entfernt. Vier unabhängige Zimmer, jedes einzeln buchbar und mit eigenem Charakter.',
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Lust auf einen Aufenthalt im Gasthof?', gitesCtaText: 'Jedes Zimmer wird unabhängig gebucht, telefonisch oder schriftlich. Wir stellen Ihren Aufenthalt gemeinsam mit Ihnen zusammen.',
    spaEyebrow: 'STILLE · RUHE · WASSER', spaTitle: 'Der Spa', spaTagline: 'Ein abgeschiedener, gedämpfter Ort, den Gästen des Gasthofs vorbehalten.',
    practiceEyebrow: 'GUT ZU WISSEN', practiceTitle: 'Zugang zum Spa',
    practice1Title: 'Täglich geöffnet', practice1Text: '10:00 – 20:00 Uhr, in privatisierten Zeitfenstern',
    practice2Title: 'Nur für Gäste', practice2Text: 'Inklusive bei Aufenthalten im Gîte, auf Anfrage im Restaurant',
    practice3Title: 'Wäsche gestellt', practice3Text: 'Bademäntel, Handtücher und Hausschuhe stehen zur Verfügung',
    ctaBookSlot: 'ZEITFENSTER BUCHEN',
    contactEyebrow: 'KONTAKT', contactTitle1: 'Schreiben Sie uns,', contactTitle2: 'oder besuchen Sie uns.',
    addressLabel: 'ADRESSE', phoneLabel: 'TELEFON', emailLabel: 'E-MAIL',
    contactHours: 'Empfang von Montag bis Sonntag, 9 – 19 Uhr.', contactHours2: 'Restaurant, Gîte und Spa: Alle Anfragen telefonisch oder per E-Mail — wir antworten innerhalb von 24 Stunden.',
    formNameLabel: 'NAME', formFirstNameLabel: 'VORNAME', formEmailLabel: 'E-MAIL', formMessageLabel: 'NACHRICHT',
    formNamePh: 'Ihr Name', formFirstNamePh: 'Ihr Vorname', formEmailPh: 'sie@beispiel.com', formMessagePh: 'Ihre Nachricht…',
    formSendBtn: 'NACHRICHT SENDEN', formNote: 'Beim Klicken auf Senden öffnet sich Ihr E-Mail-Programm mit dieser vorausgefüllten Nachricht.',
    recruitEyebrow: 'WERDEN SIE TEIL DES TEAMS', recruitTitle: 'Karriere', recruitTagline: 'Le Méandre wächst mit den Menschen, die hier arbeiten.',
    recruitParagraph: 'Wir stellen regelmäßig in der Küche, im Service sowie für die Pflege des Gasthofs und des Gîtes ein. Ist heute nichts Passendes dabei? Schicken Sie uns eine Initiativbewerbung: Wir bewahren jeden Lebenslauf auf und melden uns, sobald eine Stelle frei wird.',
    recruitCta: 'BEWERBUNG SENDEN', recruitEmailNote: 'Lebenslauf und Anschreiben an:',
    sceneEyebrow: 'BÜHNE & KUNST', sceneTitle: 'Le Méandre öffnet seine Bühne', sceneTagline: 'Sind Sie Künstler?',
    sceneParagraph: 'Sind Sie Musiker, Maler, Fotograf, Komiker oder darstellender Künstler? Möchten Sie ausstellen, auftreten oder ein Projekt mit uns entwickeln? Wir sind stets auf der Suche nach neuen Welten und neuen Sensibilitäten, die wir unseren Gästen vorstellen können.',
    sceneFormIntro: 'Stellen Sie Ihre Welt vor', sceneCta: 'MEIN PROJEKT VORSCHLAGEN',
    sceneDisciplineLabel: 'DISZIPLIN', sceneDisciplinePh: 'Musik, Malerei, Fotografie, darstellende Kunst…',
    sceneProjectLabel: 'IHR PROJEKT', sceneProjectPh: 'Beschreiben Sie Ihre Welt, Ihr Projekt, Ihre Verfügbarkeit…',
    sceneFormNote: 'Beim Klicken auf Senden öffnet sich Ihr E-Mail-Programm mit dieser vorausgefüllten Nachricht.',
    sinceWord: 'SEIT',
    phHero: 'Foto des Gasthofs — Außenansicht, Großformat', phAccRest: 'Signature-Gericht', phAccGites: 'Inneres des Gîte', phAccSpa: 'Innenpool / Spa',
    phRestHero: 'Speisesaal oder Gericht — breites Banner', phSpaHero: 'Innenpool — großformatig, immersiv', phContact: 'Foto — Zufahrt, Tor oder Lageplan',
    phAEmporter: 'Plakat des aktuellen Angebots zum Mitnehmen — Hochformat'
  },
  es: {
    navRestaurant: 'RESTAURANTE', navAEmporter: 'PARA LLEVAR', navGites: 'LA CASA RURAL', navSpa: 'SPA', navContact: 'CONTACTO',
    footerRecrutement: 'EMPLEO', footerScene: 'ESCENA Y ARTE',
    heroTagline: 'Restaurante, casa rural y spa en una antigua posada cargada de historia, en el corazón del Valle del Course.',
    cardRestTitle: 'El Restaurante', cardRestDesc: 'Una cocina refinada de temporada, entre tierra y mar.',
    cardGitesTitle: 'La Casa Rural', cardGitesDesc: 'Cuatro habitaciones independientes, reservables por separado, en la misma casa.',
    cardSpaTitle: 'El Spa', cardSpaDesc: 'Una piscina cubierta, en una calma absoluta.',
    discover: 'DESCUBRIR →',
    artEyebrow: 'BIENVENIDOS AL MÉANDRE', artTitle1: 'Un lugar cargado de historia, en el corazón', artTitle2: 'del Valle del Course.',
    artParagraph: 'Antigua posada dedicada a acoger a los viajeros, la casa ha vivido varias vidas antes de escribir hoy un nuevo capítulo bajo el nombre de Le Méandre. Restaurante, casa rural y spa se combinan aquí en un espíritu cálido y refinado — una nueva historia que se escribe a orillas del Course.',
    ctaContact: 'CONTÁCTENOS',
    eventEyebrow: 'SEMINARIOS · BODAS · RECEPCIONES', eventTitle: 'Eventos',
    eventTagline: 'La posada también se presta a sus grandes momentos: bodas campestres, seminarios de empresa, recepciones privadas o comidas familiares.',
    eventParagraph: 'Sala de recepciones, terraza, jardín y salón privado, la cocina de nuestro restaurante y la casa rural para alojar a los invitados: diseñamos cada evento a medida, desde un cóctel en el jardín hasta la cena en nuestro salón privado.',
    eventCta: 'SOLICITAR PRESUPUESTO',
    restEyebrow: 'ENTRE TIERRA Y MAR', restTitle: 'El Restaurante', restTagline: 'Una cocina refinada, entre tierra y mar, al hilo de las estaciones.',
    menuEyebrow: 'LA CARTA', menuTitle: 'El Menú',
    menuTerroirTitle: 'Menú Terruño', menuTerroirSub: 'Entrante · Plato · Postre',
    menuEstreeTitle: 'Menú Signature', menuEstreeSub: 'Degustación en seis tiempos, maridaje de vinos',
    galleryEyebrow: 'GALERÍA', galleryTitle: 'La mesa, la sala, el ambiente',
    hoursEyebrow: 'HORARIOS', hoursText: 'De miércoles a domingo', hoursLunch: 'Comida · 12:00 – 13:30 h', hoursDinner: 'Cena · 19:30 – 21:30 h', hoursClosed: 'Cerrado lunes y martes',
    cuisineEyebrow: 'LA COCINA', cuisineText: 'Refinada · Tierra y Mar', cuisineText2: 'Productos del mar y productores locales', cuisineText3: 'Carta renovada cada temporada',
    resaEyebrow: 'RESERVAS', resaText: 'Solo por teléfono',
    aemporterEyebrow: 'PARA LLEVAR', aemporterTitle: 'Para Llevar', aemporterTagline: 'La cocina del restaurante, para disfrutar en casa.',
    aemporterParagraph: 'Platos cocinados a fuego lento, entrantes y postres preparados por nuestra cocina, listos para recoger. La carta cambia según la temporada y el mercado — llámenos para conocer los platos del día.',
    aemporterHoursText: 'Recogida de miércoles a domingo', aemporterHoursLunch: '12:00 – 13:30 h', aemporterHoursDinner: '19:00 – 20:30 h',
    aemporterOrderEyebrow: 'PEDIDOS', aemporterOrderText: 'Por teléfono, preferiblemente el día anterior', aemporterCta: 'LLAMAR PARA PEDIR',
    gitesEyebrow: 'ALOJARSE EN LA POSADA', gitesTitle: 'La Casa Rural',
    gitesTagline: 'Una casa restaurada con esmero, a pocos pasos del restaurante. Cuatro habitaciones independientes, cada una reservable por separado y con su propio carácter.',
    gitesDetail1: 'Detalle 1', gitesDetail2: 'Detalle 2', gitesDetail3: 'Detalle 3',
    gitesCtaTitle: '¿Le apetece alojarse en la posada?', gitesCtaText: 'Cada habitación se reserva de forma independiente, por teléfono o por escrito. Diseñaremos su estancia junto a usted.',
    spaEyebrow: 'SILENCIO · CALMA · AGUA', spaTitle: 'El Spa', spaTagline: 'Un espacio cerrado y aterciopelado, reservado a los huéspedes de la posada.',
    practiceEyebrow: 'INFORMACIÓN PRÁCTICA', practiceTitle: 'Acceso al spa',
    practice1Title: 'Abierto todos los días', practice1Text: '10:00 – 20:00 h, en franjas privatizadas',
    practice2Title: 'Reservado a los huéspedes', practice2Text: 'Incluido en las estancias en la casa rural, bajo petición en el restaurante',
    practice3Title: 'Ropa de baño incluida', practice3Text: 'Albornoces, toallas y zapatillas a su disposición',
    ctaBookSlot: 'RESERVAR UNA FRANJA',
    contactEyebrow: 'CONTACTO', contactTitle1: 'Escríbanos,', contactTitle2: 'o venga a vernos.',
    addressLabel: 'DIRECCIÓN', phoneLabel: 'TELÉFONO', emailLabel: 'CORREO ELECTRÓNICO',
    contactHours: 'Recepción de lunes a domingo, 9 – 19 h.', contactHours2: 'Restaurante, casa rural y spa: toda solicitud por teléfono o correo electrónico — respondemos en 24 h.',
    formNameLabel: 'APELLIDO', formFirstNameLabel: 'NOMBRE', formEmailLabel: 'CORREO ELECTRÓNICO', formMessageLabel: 'MENSAJE',
    formNamePh: 'Su apellido', formFirstNamePh: 'Su nombre', formEmailPh: 'usted@ejemplo.com', formMessagePh: 'Su mensaje…',
    formSendBtn: 'ENVIAR MENSAJE', formNote: 'Al hacer clic en enviar, se abrirá su aplicación de correo con este mensaje ya redactado.',
    recruitEyebrow: 'ÚNASE A NOSOTROS', recruitTitle: 'Empleo', recruitTagline: 'Le Méandre crece con las personas que trabajan aquí.',
    recruitParagraph: 'Contratamos regularmente en cocina, en sala y para el mantenimiento de la posada y la casa rural. ¿Ningún puesto abierto le corresponde hoy? Envíenos una candidatura espontánea: guardamos cada currículum y le contactamos en cuanto se abra un puesto.',
    recruitCta: 'ENVIAR MI CANDIDATURA', recruitEmailNote: 'CV y carta de motivación a:',
    sceneEyebrow: 'ESCENA Y ARTE', sceneTitle: 'Le Méandre abre su escenario', sceneTagline: '¿Es usted artista?',
    sceneParagraph: '¿Es usted músico, pintor, fotógrafo, humorista o artista de las artes escénicas? ¿Desea exponer, actuar o imaginar un proyecto con nosotros? Siempre estamos buscando nuevos universos y nuevas sensibilidades que dar a conocer a nuestros huéspedes.',
    sceneFormIntro: 'Proponga su universo', sceneCta: 'PROPONER MI PROYECTO',
    sceneDisciplineLabel: 'DISCIPLINA', sceneDisciplinePh: 'Música, pintura, fotografía, artes escénicas…',
    sceneProjectLabel: 'SU PROYECTO', sceneProjectPh: 'Describa su universo, su proyecto, su disponibilidad…',
    sceneFormNote: 'Al hacer clic en enviar, se abrirá su aplicación de correo con este mensaje ya redactado.',
    sinceWord: 'DESDE',
    phHero: 'Foto de la posada — vista exterior, gran formato', phAccRest: 'Plato signature', phAccGites: 'Interior de la casa rural', phAccSpa: 'Piscina cubierta / spa',
    phRestHero: 'Sala del restaurante o plato — banner ancho', phSpaHero: 'Piscina cubierta — gran formato inmersivo', phContact: 'Foto — camino de acceso, portón o plano de acceso',
    phAEmporter: 'Cartel de la oferta actual para llevar — formato vertical'
  },
  nl: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'AFHALEN', navGites: 'DE GÎTE', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'VACATURES', footerScene: 'PODIUM & KUNST',
    heroTagline: 'Restaurant, gîte en spa in een voormalige pleisterplaats vol geschiedenis, in het hart van de Course-vallei.',
    cardRestTitle: 'Het Restaurant', cardRestDesc: 'Een verfijnde, seizoensgebonden keuken tussen land en zee.',
    cardGitesTitle: 'De Gîte', cardGitesDesc: 'Vier onafhankelijke kamers, apart te boeken, in hetzelfde huis.',
    cardSpaTitle: 'De Spa', cardSpaDesc: 'Een binnenzwembad, in volstrekte rust.',
    discover: 'ONTDEKKEN →',
    artEyebrow: 'WELKOM BIJ LE MÉANDRE', artTitle1: 'Een plek vol geschiedenis, in het hart van', artTitle2: 'de Course-vallei.',
    artParagraph: 'Als voormalige pleisterplaats voor reizigers heeft het huis meerdere levens gekend, voordat het vandaag een nieuw hoofdstuk schrijft onder de naam Le Méandre. Restaurant, gîte en spa komen hier samen in een warme en verfijnde sfeer — een nieuw verhaal dat zich ontvouwt langs de Course.',
    ctaContact: 'NEEM CONTACT OP',
    eventEyebrow: 'SEMINARS · BRUILOFTEN · RECEPTIES', eventTitle: 'Evenementen',
    eventTagline: 'De herberg leent zich ook voor uw bijzondere momenten: landelijke bruiloften, bedrijfsseminars, privérecepties of familiediners.',
    eventParagraph: 'Ontvangstzaal, terras, tuin en privésalon, de keuken van ons restaurant en de gîte voor de overnachting van gasten: wij stellen elk evenement op maat samen, van een cocktail in de tuin tot een diner in onze privésalon.',
    eventCta: 'OFFERTE AANVRAGEN',
    restEyebrow: 'TUSSEN LAND EN ZEE', restTitle: 'Het Restaurant', restTagline: 'Een verfijnde keuken, tussen land en zee, met de seizoenen mee.',
    menuEyebrow: 'DE KAART', menuTitle: 'Het Menu',
    menuTerroirTitle: 'Menu Terroir', menuTerroirSub: 'Voorgerecht · Hoofdgerecht · Dessert',
    menuEstreeTitle: 'Signature Menu', menuEstreeSub: 'Zesgangen proeverij, met wijnbegeleiding',
    galleryEyebrow: 'IN BEELD', galleryTitle: 'De tafel, de zaal, de sfeer',
    hoursEyebrow: 'OPENINGSTIJDEN', hoursText: 'Woensdag tot en met zondag', hoursLunch: 'Lunch · 12:00 – 13:30 uur', hoursDinner: 'Diner · 19:30 – 21:30 uur', hoursClosed: 'Gesloten op maandag en dinsdag',
    cuisineEyebrow: 'DE KEUKEN', cuisineText: 'Verfijnd · Land en Zee', cuisineText2: 'Zeeproducten en lokale producenten', cuisineText3: 'Kaart elk seizoen vernieuwd',
    resaEyebrow: 'RESERVERING', resaText: 'Uitsluitend telefonisch',
    aemporterEyebrow: 'AFHALEN', aemporterTitle: 'Afhaalgerechten', aemporterTagline: 'De keuken van het restaurant, thuis te genieten.',
    aemporterParagraph: 'Stoofgerechten, voorgerechten en desserts bereid door onze keuken, klaar om af te halen. De kaart verandert met het seizoen en het aanbod — bel ons voor de gerechten van de dag.',
    aemporterHoursText: 'Afhalen van woensdag tot zondag', aemporterHoursLunch: '12:00 – 13:30 uur', aemporterHoursDinner: '19:00 – 20:30 uur',
    aemporterOrderEyebrow: 'BESTELLEN', aemporterOrderText: 'Telefonisch, bij voorkeur de dag ervoor', aemporterCta: 'BEL OM TE BESTELLEN',
    gitesEyebrow: 'VERBLIJVEN IN DE HERBERG', gitesTitle: 'De Gîte',
    gitesTagline: 'Een zorgvuldig gerestaureerd huis, op enkele stappen van het restaurant. Vier onafhankelijke kamers, elk apart te boeken en met hun eigen karakter.',
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Zin om in de herberg te verblijven?', gitesCtaText: 'Elke kamer wordt onafhankelijk geboekt, telefonisch of schriftelijk. Wij stellen uw verblijf samen met u samen.',
    spaEyebrow: 'STILTE · RUST · WATER', spaTitle: 'De Spa', spaTagline: 'Een besloten, gedempte plek, voorbehouden aan de gasten van de herberg.',
    practiceEyebrow: 'PRAKTISCHE INFORMATIE', practiceTitle: 'Toegang tot de spa',
    practice1Title: 'Elke dag geopend', practice1Text: '10:00 – 20:00 uur, in geprivatiseerde tijdsloten',
    practice2Title: 'Voorbehouden aan gasten', practice2Text: 'Inbegrepen bij een verblijf in de gîte, op aanvraag bij het restaurant',
    practice3Title: 'Linnengoed inbegrepen', practice3Text: 'Badjassen, handdoeken en slippers ter beschikking',
    ctaBookSlot: 'TIJDSLOT BOEKEN',
    contactEyebrow: 'CONTACT', contactTitle1: 'Schrijf ons,', contactTitle2: 'of kom langs.',
    addressLabel: 'ADRES', phoneLabel: 'TELEFOON', emailLabel: 'E-MAIL',
    contactHours: 'Onthaal van maandag tot zondag, 9 – 19 uur.', contactHours2: 'Restaurant, gîte en spa: alle aanvragen telefonisch of per e-mail — wij reageren binnen 24 uur.',
    formNameLabel: 'ACHTERNAAM', formFirstNameLabel: 'VOORNAAM', formEmailLabel: 'E-MAIL', formMessageLabel: 'BERICHT',
    formNamePh: 'Uw achternaam', formFirstNamePh: 'Uw voornaam', formEmailPh: 'u@voorbeeld.com', formMessagePh: 'Uw bericht…',
    formSendBtn: 'BERICHT VERSTUREN', formNote: 'Als u op verzenden klikt, wordt uw e-mailprogramma geopend met dit vooraf ingevulde bericht.',
    recruitEyebrow: 'KOM BIJ ONS WERKEN', recruitTitle: 'Vacatures', recruitTagline: 'Le Méandre groeit met de mensen die hier werken.',
    recruitParagraph: 'Wij werven regelmatig personeel voor de keuken, de bediening en het onderhoud van de herberg en de gîte. Niets vrij dat bij u past? Stuur ons een open sollicitatie: wij bewaren elk cv en nemen contact op zodra er een functie vrijkomt.',
    recruitCta: 'MIJN SOLLICITATIE VERSTUREN', recruitEmailNote: 'Cv en motivatiebrief naar:',
    sceneEyebrow: 'PODIUM & KUNST', sceneTitle: 'Le Méandre opent zijn podium', sceneTagline: 'Bent u kunstenaar?',
    sceneParagraph: 'Bent u muzikant, schilder, fotograaf, komiek of podiumkunstenaar? Wilt u exposeren, optreden of een project met ons bedenken? Wij zijn altijd op zoek naar nieuwe werelden en nieuwe gevoeligheden om aan onze gasten te laten ontdekken.',
    sceneFormIntro: 'Stel uw wereld voor', sceneCta: 'MIJN PROJECT VOORSTELLEN',
    sceneDisciplineLabel: 'DISCIPLINE', sceneDisciplinePh: 'Muziek, schilderkunst, fotografie, podiumkunst…',
    sceneProjectLabel: 'UW PROJECT', sceneProjectPh: 'Beschrijf uw wereld, uw project, uw beschikbaarheid…',
    sceneFormNote: 'Als u op verzenden klikt, wordt uw e-mailprogramma geopend met dit vooraf ingevulde bericht.',
    sinceWord: 'SINDS',
    phHero: 'Foto van de herberg — buitenaanzicht, groot formaat', phAccRest: 'Signature gerecht', phAccGites: 'Interieur van de gîte', phAccSpa: 'Binnenzwembad / spa',
    phRestHero: 'Eetzaal of gerecht — brede banner', phSpaHero: 'Binnenzwembad — groot immersief formaat', phContact: 'Foto — oprijlaan, poort of toegangsplan',
    phAEmporter: 'Poster van het huidige afhaalaanbod — staand formaat'
  }
};

// ── Carte du restaurant (3 catégories × 3 plats) ──
window.MEANDRE_MENU = [
  { nom: { fr: 'Entrées', en: 'Starters', de: 'Vorspeisen', es: 'Entrantes', nl: 'Voorgerechten' }, plats: [
    { nom: { fr: 'Velouté de topinambour', en: 'Jerusalem artichoke velouté', de: 'Topinambur-Velouté', es: 'Velouté de topinambo', nl: 'Topinamboer-veloutésoep' }, desc: { fr: 'Noisettes torréfiées, huile de livèche', en: 'Toasted hazelnuts, lovage oil', de: 'Geröstete Haselnüsse, Liebstocköl', es: 'Avellanas tostadas, aceite de levístico', nl: 'Gebrande hazelnoten, lavasolie' }, prix: '18 €' },
    { nom: { fr: 'Foie gras de canard mi-cuit', en: 'Duck foie gras, mi-cuit', de: 'Entenfoie gras, mi-cuit', es: 'Foie gras de pato, mi-cuit', nl: 'Eendenfoie gras, mi-cuit' }, desc: { fr: 'Chutney de figues du verger, brioche toastée', en: 'Orchard fig chutney, toasted brioche', de: 'Feigenchutney aus dem Obstgarten, geröstete Brioche', es: 'Chutney de higos del huerto, brioche tostada', nl: 'Vijgenchutney uit de boomgaard, geroosterde brioche' }, prix: '24 €' },
    { nom: { fr: 'Tartare de truite', en: 'Trout tartare', de: 'Forellentatar', es: 'Tartar de trucha', nl: 'Forellentartaar' }, desc: { fr: "Crème d'aneth, pickles d'oignon rouge", en: 'Dill cream, pickled red onion', de: 'Dillcreme, eingelegte rote Zwiebeln', es: 'Crema de eneldo, encurtido de cebolla roja', nl: 'Dilroom, ingelegde rode ui' }, prix: '21 €' }] },
  { nom: { fr: 'Plats', en: 'Mains', de: 'Hauptgerichte', es: 'Platos principales', nl: 'Hoofdgerechten' }, plats: [
    { nom: { fr: 'Filet de bœuf des pâtures', en: 'Pasture-raised beef fillet', de: 'Rinderfilet von der Weide', es: 'Solomillo de ternera de pasto', nl: 'Runderfilet van de weide' }, desc: { fr: 'Jus corsé au vin rouge, légumes racines confits', en: 'Red wine jus, confit root vegetables', de: 'Kräftiger Rotweinjus, confierte Wurzelgemüse', es: 'Jugo intenso al vino tinto, verduras de raíz confitadas', nl: 'Krachtige rodewijnjus, geconfijte wortelgroenten' }, prix: '42 €' },
    { nom: { fr: 'Sandre rôti sur peau', en: 'Pan-roasted zander, crispy skin', de: 'Gebratener Zander mit knuspriger Haut', es: 'Lucioperca asada con piel crujiente', nl: 'Gebakken snoekbaars, krokante huid' }, desc: { fr: 'Beurre blanc au safran, poireaux brûlés', en: 'Saffron beurre blanc, charred leeks', de: 'Safran-Beurre-blanc, geröstete Lauch', es: 'Beurre blanc al azafrán, puerros tostados', nl: 'Saffraan-beurre-blanc, geschroeide prei' }, prix: '38 €' },
    { nom: { fr: 'Pigeon fermier en deux cuissons', en: 'Farmhouse pigeon, two ways', de: 'Bauernhof-Taube, zweifach gegart', es: 'Pichón de granja en dos cocciones', nl: 'Boerderijduif op twee bereidingswijzen' }, desc: { fr: 'Cerises acidulées, polenta crémeuse', en: 'Tart cherries, creamy polenta', de: 'Säuerliche Kirschen, cremige Polenta', es: 'Cerezas ácidas, polenta cremosa', nl: 'Zurige kersen, romige polenta' }, prix: '44 €' }] },
  { nom: { fr: 'Desserts', en: 'Desserts', de: 'Desserts', es: 'Postres', nl: 'Desserts' }, plats: [
    { nom: { fr: 'Soufflé chaud au Grand Marnier', en: 'Warm Grand Marnier soufflé', de: 'Warmes Grand-Marnier-Soufflé', es: 'Suflé caliente de Grand Marnier', nl: 'Warme Grand Marnier-soufflé' }, desc: { fr: 'Minute, pour deux personnes', en: 'Made to order, for two', de: 'Frisch zubereitet, für zwei Personen', es: 'Al momento, para dos personas', nl: 'Op het moment bereid, voor twee personen' }, prix: '16 €' },
    { nom: { fr: 'Tarte fine aux poires', en: 'Thin pear tart', de: 'Feine Birnentarte', es: 'Tarta fina de peras', nl: 'Fijne perentaart' }, desc: { fr: 'Glace miel-lavande maison', en: 'House-made honey-lavender ice cream', de: 'Hausgemachtes Honig-Lavendel-Eis', es: 'Helado de miel y lavanda de la casa', nl: 'Huisgemaakt honing-lavendelijs' }, prix: '14 €' },
    { nom: { fr: 'Sphère chocolat grand cru', en: 'Grand cru chocolate sphere', de: 'Grand-Cru-Schokoladenkugel', es: 'Esfera de chocolate grand cru', nl: 'Grand cru chocoladebol' }, desc: { fr: "Cœur caramel, feuille d'or", en: 'Caramel heart, gold leaf', de: 'Karamellkern, Blattgold', es: 'Corazón de caramelo, pan de oro', nl: 'Karamelhart, bladgoud' }, prix: '17 €' }] }
];

// ── Le gîte (4 chambres louables indépendamment, au sein d'une même maison) ──
// (slotA-D sont les clés de persistance des photos déposées dans chaque
// image-slot — ne pas les modifier sans mettre à jour le gabarit)
window.MEANDRE_GITES = [
  { num: '01',
    nom: { fr: 'Chambre 1', en: 'Room 1', de: 'Zimmer 1', es: 'Habitación 1', nl: 'Kamer 1' },
    capacite: { fr: 'CHAMBRE INDÉPENDANTE', en: 'INDEPENDENT ROOM', de: 'UNABHÄNGIGES ZIMMER', es: 'HABITACIÓN INDEPENDIENTE', nl: 'ONAFHANKELIJKE KAMER' },
    desc: { fr: "L'une des quatre chambres du gîte, aménagée avec soin et réservable indépendamment des trois autres.", en: "One of the cottage's four rooms, carefully appointed and bookable independently of the other three.", de: 'Eines der vier Zimmer des Gîte, sorgfältig eingerichtet und unabhängig von den anderen drei buchbar.', es: 'Una de las cuatro habitaciones de la casa rural, cuidada con esmero y reservable de forma independiente de las otras tres.', nl: 'Een van de vier kamers van de gîte, zorgvuldig ingericht en onafhankelijk van de andere drie te boeken.' },
    equip: { fr: [], en: [], de: [], es: [], nl: [] },
    slotA: 'site-g1a', slotB: 'site-g1b', slotC: 'site-g1c', slotD: 'site-g1d', srcA: './images/gite1_1.JPG',
    phA: { fr: 'Chambre 1 — vue', en: 'Room 1 — view', de: 'Zimmer 1 — Ansicht', es: 'Habitación 1 — vista', nl: 'Kamer 1 — aanzicht' } },
  { num: '02',
    nom: { fr: 'Chambre 2', en: 'Room 2', de: 'Zimmer 2', es: 'Habitación 2', nl: 'Kamer 2' },
    capacite: { fr: 'CHAMBRE INDÉPENDANTE', en: 'INDEPENDENT ROOM', de: 'UNABHÄNGIGES ZIMMER', es: 'HABITACIÓN INDEPENDIENTE', nl: 'ONAFHANKELIJKE KAMER' },
    desc: { fr: "L'une des quatre chambres du gîte, aménagée avec soin et réservable indépendamment des trois autres.", en: "One of the cottage's four rooms, carefully appointed and bookable independently of the other three.", de: 'Eines der vier Zimmer des Gîte, sorgfältig eingerichtet und unabhängig von den anderen drei buchbar.', es: 'Una de las cuatro habitaciones de la casa rural, cuidada con esmero y reservable de forma independiente de las otras tres.', nl: 'Een van de vier kamers van de gîte, zorgvuldig ingericht en onafhankelijk van de andere drie te boeken.' },
    equip: { fr: [], en: [], de: [], es: [], nl: [] },
    slotA: 'site-g2a', slotB: 'site-g2b', slotC: 'site-g2c', slotD: 'site-g2d', srcA: './images/gite2_1.JPG', srcB: './images/gite2_2.JPG',
    phA: { fr: 'Chambre 2 — vue', en: 'Room 2 — view', de: 'Zimmer 2 — Ansicht', es: 'Habitación 2 — vista', nl: 'Kamer 2 — aanzicht' } },
  { num: '03',
    nom: { fr: 'Chambre 3', en: 'Room 3', de: 'Zimmer 3', es: 'Habitación 3', nl: 'Kamer 3' },
    capacite: { fr: 'CHAMBRE INDÉPENDANTE', en: 'INDEPENDENT ROOM', de: 'UNABHÄNGIGES ZIMMER', es: 'HABITACIÓN INDEPENDIENTE', nl: 'ONAFHANKELIJKE KAMER' },
    desc: { fr: "L'une des quatre chambres du gîte, aménagée avec soin et réservable indépendamment des trois autres.", en: "One of the cottage's four rooms, carefully appointed and bookable independently of the other three.", de: 'Eines der vier Zimmer des Gîte, sorgfältig eingerichtet und unabhängig von den anderen drei buchbar.', es: 'Una de las cuatro habitaciones de la casa rural, cuidada con esmero y reservable de forma independiente de las otras tres.', nl: 'Een van de vier kamers van de gîte, zorgvuldig ingericht en onafhankelijk van de andere drie te boeken.' },
    equip: { fr: [], en: [], de: [], es: [], nl: [] },
    slotA: 'site-g3a', slotB: 'site-g3b', slotC: 'site-g3c', slotD: 'site-g3d', srcA: './images/gite3_1.JPG', srcB: './images/gite3_2.JPG',
    phA: { fr: 'Chambre 3 — vue', en: 'Room 3 — view', de: 'Zimmer 3 — Ansicht', es: 'Habitación 3 — vista', nl: 'Kamer 3 — aanzicht' } },
  { num: '04',
    nom: { fr: 'Chambre 4', en: 'Room 4', de: 'Zimmer 4', es: 'Habitación 4', nl: 'Kamer 4' },
    capacite: { fr: 'CHAMBRE INDÉPENDANTE', en: 'INDEPENDENT ROOM', de: 'UNABHÄNGIGES ZIMMER', es: 'HABITACIÓN INDEPENDIENTE', nl: 'ONAFHANKELIJKE KAMER' },
    desc: { fr: "L'une des quatre chambres du gîte, aménagée avec soin et réservable indépendamment des trois autres.", en: "One of the cottage's four rooms, carefully appointed and bookable independently of the other three.", de: 'Eines der vier Zimmer des Gîte, sorgfältig eingerichtet und unabhängig von den anderen drei buchbar.', es: 'Una de las cuatro habitaciones de la casa rural, cuidada con esmero y reservable de forma independiente de las otras tres.', nl: 'Een van de vier kamers van de gîte, zorgvuldig ingericht en onafhankelijk van de andere drie te boeken.' },
    equip: { fr: [], en: [], de: [], es: [], nl: [] },
    slotA: 'site-g4a', slotB: 'site-g4b', slotC: 'site-g4c', slotD: 'site-g4d', srcA: './images/gite4_1.JPG', srcB: './images/gite4_2.JPG',
    phA: { fr: 'Chambre 4 — vue', en: 'Room 4 — view', de: 'Zimmer 4 — Ansicht', es: 'Habitación 4 — vista', nl: 'Kamer 4 — aanzicht' } }
];

// ── Le spa (une piscine intérieure) ── (slot = clé de persistance de la photo déposée)
window.MEANDRE_SPAS = [
  { nom: { fr: 'La Piscine intérieure', en: 'The Indoor Pool', de: 'Der Innenpool', es: 'La Piscina Interior', nl: 'Het Binnenzwembad' },
    sur: { fr: 'BASSIN · 28°C', en: 'POOL · 82°F', de: 'BECKEN · 28°C', es: 'PISCINA · 28°C', nl: 'BAD · 28°C' },
    desc: { fr: "Un bassin de nage de quinze mètres sous verrière, chauffé toute l'année. La lumière du jardin entre à travers les arbres ; on n'entend que l'eau.", en: 'A fifteen-metre lap pool beneath a glass roof, heated year-round. Light from the garden filters through the trees; all you hear is the water.', de: 'Ein fünfzehn Meter langes Schwimmbecken unter einem Glasdach, ganzjährig beheizt. Das Licht des Gartens fällt durch die Bäume; man hört nur das Wasser.', es: 'Una piscina de natación de quince metros bajo una cristalera, climatizada todo el año. La luz del jardín se filtra entre los árboles; solo se oye el agua.', nl: 'Een vijftien meter lang zwembad onder een glazen overkapping, het hele jaar verwarmd. Het licht van de tuin valt door de bomen; je hoort alleen het water.' },
    info: { fr: 'Longueur 15 m · Profondeur 1,40 m', en: 'Length 15 m · Depth 1.4 m', de: 'Länge 15 m · Tiefe 1,40 m', es: 'Longitud 15 m · Profundidad 1,40 m', nl: 'Lengte 15 m · Diepte 1,40 m' },
    slot: 'site-spa-piscine', src: '', ph: { fr: 'Piscine intérieure', en: 'Indoor pool', de: 'Innenpool', es: 'Piscina interior', nl: 'Binnenzwembad' }, dir: 'ltr' }
];

// ── Réservoir de légendes pour le carrousel photo du restaurant ──
// (nbPhotosCarrousel, une prop éditable, détermine combien d'entre elles sont utilisées)
window.MEANDRE_POOL = [
  { slot: 'site-car-1', src: './images/restaurant1.JPEG', ph: { fr: 'Photo 1 — plat', en: 'Photo 1 — dish', de: 'Foto 1 — Gericht', es: 'Foto 1 — plato', nl: 'Foto 1 — gerecht' } },
  { slot: 'site-car-2', src: './images/restaurant2.JPEG', ph: { fr: 'Photo 2 — salle', en: 'Photo 2 — dining room', de: 'Foto 2 — Speisesaal', es: 'Foto 2 — sala', nl: 'Foto 2 — eetzaal' } },
  { slot: 'site-car-3', ph: { fr: 'Photo 3 — ambiance', en: 'Photo 3 — atmosphere', de: 'Foto 3 — Atmosphäre', es: 'Foto 3 — ambiente', nl: 'Foto 3 — sfeer' } },
  { slot: 'site-car-4', ph: { fr: 'Photo 4 — dessert', en: 'Photo 4 — dessert', de: 'Foto 4 — Dessert', es: 'Foto 4 — postre', nl: 'Foto 4 — dessert' } },
  { slot: 'site-car-5', ph: { fr: 'Photo 5 — terrasse', en: 'Photo 5 — terrace', de: 'Foto 5 — Terrasse', es: 'Foto 5 — terraza', nl: 'Foto 5 — terras' } },
  { slot: 'site-car-6', ph: { fr: 'Photo 6 — cave', en: 'Photo 6 — cellar', de: 'Foto 6 — Weinkeller', es: 'Foto 6 — bodega', nl: 'Foto 6 — kelder' } },
  { slot: 'site-car-7', ph: { fr: 'Photo 7 — cuisine', en: 'Photo 7 — kitchen', de: 'Foto 7 — Küche', es: 'Foto 7 — cocina', nl: 'Foto 7 — keuken' } },
  { slot: 'site-car-8', ph: { fr: 'Photo 8 — détail', en: 'Photo 8 — detail', de: 'Foto 8 — Detail', es: 'Foto 8 — detalle', nl: 'Foto 8 — detail' } }
];

// ── Recrutement : postes ouverts (liste vide = candidatures spontanées uniquement) ──
window.MEANDRE_JOBS = [];
