// Le Méandre — contenu et données du site (français + anglais).
// Chargé en <script> classique avant que index.html n'évalue son
// Component : tout ici est posé sur `window` pour être lu depuis
// Component.renderVals(). C'est le fichier à modifier pour changer un texte,
// un plat de la carte, un gîte ou une traduction — pas besoin de toucher au
// gabarit HTML dans index.html pour ça.

// ── Easing (fonctions de courbe d'animation), utilisées par l'écran de
//    chargement dans Component._loaderVals(). ──
window.MeandreEasing = {
  outCubic: (t) => 1 - Math.pow(1 - t, 3),
  inOutSine: (t) => -(Math.cos(Math.PI * t) - 1) / 2,
  inOutCubic: (t) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2),
  clamp: (v, a, b) => Math.min(b, Math.max(a, v)),
};

// ── Tracé vectoriel du logo pour l'écran de chargement ──
// 3 volutes qui se dessinent comme une branche qui pousse.
// Chaque entrée : [d, largeur, début, durée] sur la progression de la scène "Tourbillon".
window.MEANDRE_LOADER_STROKES = [
  ['M 418 452 C 255 494, 76 432, 54 286 C 33 152, 138 42, 260 47 C 332 51, 346 112, 299 135 C 268 150, 243 128, 252 104', 9, 0.00, 0.42],
  ['M 100 248 C 118 358, 232 414, 342 363 C 400 336, 418 292, 398 268', 8, 0.22, 0.30],
  ['M 366 260 C 462 296, 492 396, 434 456 C 419 470, 400 466, 404 450', 8, 0.40, 0.28],
];
// feuilles : [x, y, rotation, échelle, début] — chacune se dessine puis se remplit
window.MEANDRE_LOADER_LEAVES = [
  [42, 82, -32, 1.15, 0.50], [102, 58, -4, 0.8, 0.56],
  [398, 88, 24, 1.0, 0.60], [448, 162, 62, 0.9, 0.66],
  [268, 332, 168, 1.0, 0.63], [150, 322, 198, 0.8, 0.70],
];

// ── Textes de l'interface (nav, en-têtes, appels à l'action, légendes) ──
window.MEANDRE_UI = {
  fr: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'À EMPORTER', navGites: 'GÎTES', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'RECRUTEMENT',
    heroTagline: "Table gastronomique, gîtes de caractère et spa — un art de vivre au cœur des 7 vallées.",
    cardRestTitle: 'Le Restaurant', cardRestDesc: 'Une cuisine gastronomique de terroir, au fil des saisons.',
    cardGitesTitle: 'Les Gîtes', cardGitesDesc: 'Quatre maisons de caractère pour prolonger le séjour.',
    cardSpaTitle: 'Le Spa', cardSpaDesc: 'Hammam, sauna et piscine intérieure, dans une quiétude absolue.',
    discover: 'DÉCOUVRIR →',
    artEyebrow: "L'ART DE RECEVOIR", artTitle1: 'Un domaine familial où chaque séjour', artTitle2: 'se vit comme une parenthèse.',
    artParagraph: "Entre étangs et forêts, ce domaine familial cultive depuis cinq générations une hospitalité discrète : une table exigeante, des maisons pleines d'âme et un spa dédié au repos.",
    ctaContact: 'NOUS CONTACTER',
    eventEyebrow: 'SÉMINAIRES · MARIAGES · RÉCEPTIONS', eventTitle: "L'Événementiel",
    eventTagline: "Le domaine se prête aussi à vos temps forts : mariages champêtres, séminaires d'entreprise, réceptions privées ou repas de famille.",
    eventParagraph: "Salle de réception, terrasse et parc du domaine, cuisine du restaurant et gîtes pour l'hébergement des invités : nous composons chaque événement sur mesure, du cocktail dans le parc au dîner assis pour cent convives.",
    eventCta: 'DEMANDER UN DEVIS',
    restEyebrow: 'GASTRONOMIE DE TERROIR', restTitle: 'Le Restaurant', restTagline: "Une cuisine de saison, enracinée dans le terroir du domaine.",
    menuEyebrow: 'LA CARTE', menuTitle: 'Le Menu',
    menuTerroirTitle: 'Menu Terroir', menuTerroirSub: 'Entrée · Plat · Dessert',
    menuEstreeTitle: 'Menu Signature', menuEstreeSub: 'Dégustation en six temps, accords mets & vins',
    galleryEyebrow: 'EN IMAGES', galleryTitle: "La table, la salle, l'ambiance",
    hoursEyebrow: 'HORAIRES', hoursText: 'Du mercredi au dimanche', hoursLunch: 'Déjeuner · 12h00 – 13h30', hoursDinner: 'Dîner · 19h30 – 21h30', hoursClosed: 'Fermé lundi et mardi',
    cuisineEyebrow: 'LA CUISINE', cuisineText: 'Gastronomique · Terroir', cuisineText2: 'Produits du domaine et de producteurs voisins', cuisineText3: 'Carte renouvelée à chaque saison',
    resaEyebrow: 'RÉSERVATION', resaText: 'Par téléphone uniquement',
    aemporterEyebrow: 'À EMPORTER', aemporterTitle: 'La Table à Emporter', aemporterTagline: 'La cuisine du restaurant, à savourer chez vous.',
    aemporterParagraph: 'Plats mijotés, entrées et desserts préparés par notre cuisine, à récupérer sur place. La carte change selon la saison et les arrivages — appelez-nous pour connaître les plats du jour.',
    aemporterHoursText: 'Retrait du mercredi au dimanche', aemporterHoursLunch: '12h00 – 13h30', aemporterHoursDinner: '19h00 – 20h30',
    aemporterOrderEyebrow: 'COMMANDE', aemporterOrderText: 'Par téléphone, la veille de préférence', aemporterCta: 'APPELER POUR COMMANDER',
    gitesEyebrow: 'SÉJOURNER AU DOMAINE', gitesTitle: 'Les Gîtes',
    gitesTagline: 'Quatre maisons restaurées avec soin, réparties dans le parc du domaine. Chacune a son caractère ; toutes partagent le même goût du calme et de la matière.',
    gitesDetail1: 'Détail 1', gitesDetail2: 'Détail 2', gitesDetail3: 'Détail 3',
    gitesCtaTitle: 'Envie de séjourner au domaine ?', gitesCtaText: 'Les gîtes se réservent simplement, par téléphone ou par écrit. Nous composerons votre séjour avec vous.',
    spaEyebrow: 'SILENCE · CHALEUR · EAU', spaTitle: 'Le Spa', spaTagline: 'Un lieu clos, feutré, réservé aux hôtes du domaine.',
    practiceEyebrow: 'EN PRATIQUE', practiceTitle: 'Accès au spa',
    practice1Title: 'Ouvert tous les jours', practice1Text: '10h00 – 20h00, sur créneaux privatisés',
    practice2Title: 'Réservé aux hôtes', practice2Text: 'Inclus pour les séjours en gîte, sur demande au restaurant',
    practice3Title: 'Linge fourni', practice3Text: 'Peignoirs, serviettes et chaussons à disposition',
    ctaBookSlot: 'RÉSERVER UN CRÉNEAU',
    contactEyebrow: 'CONTACT', contactTitle1: 'Écrivez-nous,', contactTitle2: 'ou passez nous voir.',
    addressLabel: 'ADRESSE', phoneLabel: 'TÉLÉPHONE', emailLabel: 'EMAIL',
    contactHours: 'Accueil du lundi au dimanche, 9h – 19h.', contactHours2: 'Restaurant, gîtes et spa : toute demande se fait par téléphone ou email — nous répondons sous 24h.',
    formNameLabel: 'NOM', formFirstNameLabel: 'PRÉNOM', formEmailLabel: 'EMAIL', formMessageLabel: 'MESSAGE',
    formNamePh: 'Votre nom', formFirstNamePh: 'Votre prénom', formEmailPh: 'vous@exemple.com', formMessagePh: 'Votre message…',
    formSendBtn: 'ENVOYER LE MESSAGE', formNote: "En cliquant sur envoyer, votre messagerie s'ouvrira avec ce message pré-rempli.",
    recruitEyebrow: 'REJOIGNEZ-NOUS', recruitTitle: 'Recrutement', recruitTagline: 'Le Méandre grandit avec les personnes qui y travaillent.',
    recruitParagraph: "Nous recrutons régulièrement en cuisine, en salle et pour l'entretien du domaine et des gîtes. Aucun poste ouvert ne vous correspond aujourd'hui ? Envoyez-nous une candidature spontanée : nous gardons chaque CV et reprenons contact dès qu'un poste s'ouvre.",
    recruitCta: 'ENVOYER MA CANDIDATURE', recruitEmailNote: 'CV et lettre de motivation à :',
    sinceWord: 'DEPUIS',
    phHero: 'Photo du domaine — vue extérieure, grand format', phAccRest: 'Plat signature', phAccGites: "Intérieur d'un gîte", phAccSpa: 'Piscine intérieure / spa',
    phRestHero: 'Salle du restaurant ou plat — bandeau large', phSpaHero: 'Piscine intérieure — grand format immersif', phContact: "Photo — allée, portail ou plan d'accès",
    phAEmporter: 'Plats à emporter — packaging ou plat du jour'
  },
  en: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'TAKEAWAY', navGites: 'COTTAGES', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'CAREERS',
    heroTagline: 'Fine dining, characterful cottages and a spa — a way of life at the heart of the Seven Valleys.',
    cardRestTitle: 'The Restaurant', cardRestDesc: 'Seasonal fine dining rooted in local terroir.',
    cardGitesTitle: 'The Cottages', cardGitesDesc: 'Four characterful houses to extend your stay.',
    cardSpaTitle: 'The Spa', cardSpaDesc: 'Hammam, sauna and indoor pool, in absolute quiet.',
    discover: 'DISCOVER →',
    artEyebrow: 'THE ART OF HOSPITALITY', artTitle1: 'A family estate where every stay', artTitle2: 'feels like a pause from the world.',
    artParagraph: "Between ponds and forests, this family estate has cultivated quiet hospitality for five generations: a demanding table, houses full of character, and a spa devoted to rest.",
    ctaContact: 'CONTACT US',
    eventEyebrow: 'SEMINARS · WEDDINGS · RECEPTIONS', eventTitle: 'Events',
    eventTagline: 'The estate also lends itself to your milestone moments: countryside weddings, corporate seminars, private receptions or family gatherings.',
    eventParagraph: "Reception room, terrace and estate grounds, our restaurant's kitchen and cottages for guest accommodation: we tailor every event, from a cocktail in the park to a seated dinner for a hundred guests.",
    eventCta: 'REQUEST A QUOTE',
    restEyebrow: 'FARM-TO-TABLE DINING', restTitle: 'The Restaurant', restTagline: "Seasonal cooking, rooted in the estate's terroir.",
    menuEyebrow: 'THE MENU', menuTitle: 'The Menu',
    menuTerroirTitle: 'Terroir Menu', menuTerroirSub: 'Starter · Main · Dessert',
    menuEstreeTitle: 'Signature Menu', menuEstreeSub: 'Six-course tasting menu, wine pairings',
    galleryEyebrow: 'GALLERY', galleryTitle: 'The table, the room, the atmosphere',
    hoursEyebrow: 'HOURS', hoursText: 'Wednesday to Sunday', hoursLunch: 'Lunch · 12:00 – 1:30 PM', hoursDinner: 'Dinner · 7:30 – 9:30 PM', hoursClosed: 'Closed Monday and Tuesday',
    cuisineEyebrow: 'THE KITCHEN', cuisineText: 'Fine dining · Terroir', cuisineText2: 'Estate produce and neighbouring producers', cuisineText3: 'Menu refreshed every season',
    resaEyebrow: 'RESERVATIONS', resaText: 'By phone only',
    aemporterEyebrow: 'TAKEAWAY', aemporterTitle: 'Takeaway', aemporterTagline: "The restaurant's cooking, to enjoy at home.",
    aemporterParagraph: 'Slow-cooked dishes, starters and desserts prepared by our kitchen, ready for pickup. The menu changes with the season and the market — call us to hear the dishes of the day.',
    aemporterHoursText: 'Pickup Wednesday to Sunday', aemporterHoursLunch: '12:00 – 1:30 PM', aemporterHoursDinner: '7:00 – 8:30 PM',
    aemporterOrderEyebrow: 'ORDERING', aemporterOrderText: 'By phone, ideally the day before', aemporterCta: 'CALL TO ORDER',
    gitesEyebrow: 'STAY ON THE ESTATE', gitesTitle: 'The Cottages',
    gitesTagline: "Four carefully restored houses scattered across the estate's grounds. Each has its own character; all share the same taste for calm and craftsmanship.",
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Fancy a stay on the estate?', gitesCtaText: "Booking a cottage is simple, by phone or in writing. We'll put together your stay with you.",
    spaEyebrow: 'SILENCE · WARMTH · WATER', spaTitle: 'The Spa', spaTagline: 'A hushed, enclosed retreat reserved for estate guests.',
    practiceEyebrow: 'GOOD TO KNOW', practiceTitle: 'Spa access',
    practice1Title: 'Open every day', practice1Text: '10:00 AM – 8:00 PM, in private slots',
    practice2Title: 'Reserved for guests', practice2Text: 'Included with cottage stays, on request at the restaurant',
    practice3Title: 'Linens provided', practice3Text: 'Robes, towels and slippers provided',
    ctaBookSlot: 'BOOK A SLOT',
    contactEyebrow: 'CONTACT', contactTitle1: 'Write to us,', contactTitle2: 'or come see us.',
    addressLabel: 'ADDRESS', phoneLabel: 'PHONE', emailLabel: 'EMAIL',
    contactHours: 'Open Monday to Sunday, 9 AM – 7 PM.', contactHours2: 'Restaurant, cottages and spa: all requests by phone or email — we reply within 24h.',
    formNameLabel: 'LAST NAME', formFirstNameLabel: 'FIRST NAME', formEmailLabel: 'EMAIL', formMessageLabel: 'MESSAGE',
    formNamePh: 'Your last name', formFirstNamePh: 'Your first name', formEmailPh: 'you@example.com', formMessagePh: 'Your message…',
    formSendBtn: 'SEND MESSAGE', formNote: 'Clicking send will open your mail app with this message pre-filled.',
    recruitEyebrow: 'JOIN US', recruitTitle: 'Careers', recruitTagline: 'Le Méandre grows with the people who work here.',
    recruitParagraph: 'We regularly hire in the kitchen, the dining room, and for the upkeep of the estate and cottages. Nothing open that matches you today? Send us a spontaneous application: we keep every CV on file and get back in touch as soon as a position opens.',
    recruitCta: 'SEND MY APPLICATION', recruitEmailNote: 'CV and cover letter to:',
    sinceWord: 'SINCE',
    phHero: 'Estate photo — exterior view, large format', phAccRest: 'Signature dish', phAccGites: 'Cottage interior', phAccSpa: 'Indoor pool / spa',
    phRestHero: 'Dining room or dish — wide banner', phSpaHero: 'Indoor pool — large immersive format', phContact: 'Photo — driveway, gate or access map',
    phAEmporter: 'Takeaway dishes — packaging or dish of the day'
  },
  de: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'ZUM MITNEHMEN', navGites: 'GÎTES', navSpa: 'SPA', navContact: 'KONTAKT',
    footerRecrutement: 'KARRIERE',
    heroTagline: 'Gehobene Küche, charaktervolle Gîtes und ein Spa — eine Lebenskunst im Herzen der Sept Vallées.',
    cardRestTitle: 'Das Restaurant', cardRestDesc: 'Eine saisonale Gourmetküche, verwurzelt im Terroir.',
    cardGitesTitle: 'Die Gîtes', cardGitesDesc: 'Vier charaktervolle Häuser, um den Aufenthalt zu verlängern.',
    cardSpaTitle: 'Der Spa', cardSpaDesc: 'Hammam, Sauna und Innenpool, in vollkommener Ruhe.',
    discover: 'ENTDECKEN →',
    artEyebrow: 'DIE KUNST DES GASTGEBENS', artTitle1: 'Ein Familienanwesen, auf dem jeder Aufenthalt', artTitle2: 'wie eine Auszeit vom Alltag wirkt.',
    artParagraph: 'Zwischen Teichen und Wäldern pflegt dieses Familienanwesen seit fünf Generationen eine diskrete Gastfreundschaft: eine anspruchsvolle Küche, Häuser voller Seele und ein Spa, das ganz der Ruhe gewidmet ist.',
    ctaContact: 'KONTAKTIEREN SIE UNS',
    eventEyebrow: 'SEMINARE · HOCHZEITEN · EMPFÄNGE', eventTitle: 'Veranstaltungen',
    eventTagline: 'Das Anwesen eignet sich auch für Ihre besonderen Momente: Landhochzeiten, Firmenseminare, private Empfänge oder Familienfeiern.',
    eventParagraph: 'Empfangssaal, Terrasse und Parkgelände, die Küche unseres Restaurants und die Gîtes für die Unterbringung der Gäste: Wir gestalten jede Veranstaltung individuell, vom Cocktailempfang im Park bis zum Sitzdinner für hundert Gäste.',
    eventCta: 'ANGEBOT ANFORDERN',
    restEyebrow: 'REGIONALE GOURMETKÜCHE', restTitle: 'Das Restaurant', restTagline: 'Eine saisonale Küche, verwurzelt im Terroir des Anwesens.',
    menuEyebrow: 'DIE KARTE', menuTitle: 'Die Speisekarte',
    menuTerroirTitle: 'Menü Terroir', menuTerroirSub: 'Vorspeise · Hauptgang · Dessert',
    menuEstreeTitle: 'Signature-Menü', menuEstreeSub: 'Sechsgängiges Degustationsmenü mit Weinbegleitung',
    galleryEyebrow: 'BILDER', galleryTitle: 'Die Tafel, der Saal, die Atmosphäre',
    hoursEyebrow: 'ÖFFNUNGSZEITEN', hoursText: 'Mittwoch bis Sonntag', hoursLunch: 'Mittagessen · 12:00 – 13:30 Uhr', hoursDinner: 'Abendessen · 19:30 – 21:30 Uhr', hoursClosed: 'Montag und Dienstag geschlossen',
    cuisineEyebrow: 'DIE KÜCHE', cuisineText: 'Gehoben · Terroir', cuisineText2: 'Produkte vom Anwesen und benachbarten Erzeugern', cuisineText3: 'Karte wechselt jede Saison',
    resaEyebrow: 'RESERVIERUNG', resaText: 'Nur telefonisch',
    aemporterEyebrow: 'ZUM MITNEHMEN', aemporterTitle: 'Gerichte zum Mitnehmen', aemporterTagline: 'Die Küche des Restaurants, zu Hause genießen.',
    aemporterParagraph: 'Geschmorte Gerichte, Vorspeisen und Desserts, zubereitet von unserer Küche und zur Abholung bereit. Die Karte ändert sich je nach Saison und Angebot — rufen Sie uns an, um die Tagesgerichte zu erfahren.',
    aemporterHoursText: 'Abholung Mittwoch bis Sonntag', aemporterHoursLunch: '12:00 – 13:30 Uhr', aemporterHoursDinner: '19:00 – 20:30 Uhr',
    aemporterOrderEyebrow: 'BESTELLUNG', aemporterOrderText: 'Telefonisch, idealerweise am Vortag', aemporterCta: 'TELEFONISCH BESTELLEN',
    gitesEyebrow: 'AUFENTHALT AUF DEM ANWESEN', gitesTitle: 'Die Gîtes',
    gitesTagline: 'Vier sorgfältig restaurierte Häuser, verteilt im Park des Anwesens. Jedes hat seinen eigenen Charakter; alle teilen denselben Sinn für Ruhe und Materialität.',
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Lust auf einen Aufenthalt auf dem Anwesen?', gitesCtaText: 'Die Gîtes lassen sich ganz einfach buchen, telefonisch oder schriftlich. Wir stellen Ihren Aufenthalt gemeinsam mit Ihnen zusammen.',
    spaEyebrow: 'STILLE · WÄRME · WASSER', spaTitle: 'Der Spa', spaTagline: 'Ein abgeschiedener, gedämpfter Ort, den Gästen des Anwesens vorbehalten.',
    practiceEyebrow: 'GUT ZU WISSEN', practiceTitle: 'Zugang zum Spa',
    practice1Title: 'Täglich geöffnet', practice1Text: '10:00 – 20:00 Uhr, in privatisierten Zeitfenstern',
    practice2Title: 'Nur für Gäste', practice2Text: 'Inklusive bei Aufenthalten in den Gîtes, auf Anfrage im Restaurant',
    practice3Title: 'Wäsche gestellt', practice3Text: 'Bademäntel, Handtücher und Hausschuhe stehen zur Verfügung',
    ctaBookSlot: 'ZEITFENSTER BUCHEN',
    contactEyebrow: 'KONTAKT', contactTitle1: 'Schreiben Sie uns,', contactTitle2: 'oder besuchen Sie uns.',
    addressLabel: 'ADRESSE', phoneLabel: 'TELEFON', emailLabel: 'E-MAIL',
    contactHours: 'Empfang von Montag bis Sonntag, 9 – 19 Uhr.', contactHours2: 'Restaurant, Gîtes und Spa: Alle Anfragen telefonisch oder per E-Mail — wir antworten innerhalb von 24 Stunden.',
    formNameLabel: 'NAME', formFirstNameLabel: 'VORNAME', formEmailLabel: 'E-MAIL', formMessageLabel: 'NACHRICHT',
    formNamePh: 'Ihr Name', formFirstNamePh: 'Ihr Vorname', formEmailPh: 'sie@beispiel.com', formMessagePh: 'Ihre Nachricht…',
    formSendBtn: 'NACHRICHT SENDEN', formNote: 'Beim Klicken auf Senden öffnet sich Ihr E-Mail-Programm mit dieser vorausgefüllten Nachricht.',
    recruitEyebrow: 'WERDEN SIE TEIL DES TEAMS', recruitTitle: 'Karriere', recruitTagline: 'Le Méandre wächst mit den Menschen, die hier arbeiten.',
    recruitParagraph: 'Wir stellen regelmäßig in der Küche, im Service sowie für die Pflege des Anwesens und der Gîtes ein. Ist heute nichts Passendes dabei? Schicken Sie uns eine Initiativbewerbung: Wir bewahren jeden Lebenslauf auf und melden uns, sobald eine Stelle frei wird.',
    recruitCta: 'BEWERBUNG SENDEN', recruitEmailNote: 'Lebenslauf und Anschreiben an:',
    sinceWord: 'SEIT',
    phHero: 'Foto des Anwesens — Außenansicht, Großformat', phAccRest: 'Signature-Gericht', phAccGites: 'Inneres eines Gîte', phAccSpa: 'Innenpool / Spa',
    phRestHero: 'Speisesaal oder Gericht — breites Banner', phSpaHero: 'Innenpool — großformatig, immersiv', phContact: 'Foto — Zufahrt, Tor oder Lageplan',
    phAEmporter: 'Gerichte zum Mitnehmen — Verpackung oder Tagesgericht'
  },
  es: {
    navRestaurant: 'RESTAURANTE', navAEmporter: 'PARA LLEVAR', navGites: 'CASAS RURALES', navSpa: 'SPA', navContact: 'CONTACTO',
    footerRecrutement: 'EMPLEO',
    heroTagline: 'Alta cocina, casas rurales con carácter y spa — un arte de vivir en el corazón de las Siete Valles.',
    cardRestTitle: 'El Restaurante', cardRestDesc: 'Una cocina gastronómica de temporada, arraigada en el terruño.',
    cardGitesTitle: 'Las Casas Rurales', cardGitesDesc: 'Cuatro casas con carácter para prolongar la estancia.',
    cardSpaTitle: 'El Spa', cardSpaDesc: 'Hammam, sauna y piscina cubierta, en una calma absoluta.',
    discover: 'DESCUBRIR →',
    artEyebrow: 'EL ARTE DE RECIBIR', artTitle1: 'Una finca familiar donde cada estancia', artTitle2: 'se vive como un paréntesis.',
    artParagraph: 'Entre estanques y bosques, esta finca familiar cultiva desde hace cinco generaciones una hospitalidad discreta: una mesa exigente, casas llenas de alma y un spa dedicado al descanso.',
    ctaContact: 'CONTÁCTENOS',
    eventEyebrow: 'SEMINARIOS · BODAS · RECEPCIONES', eventTitle: 'Eventos',
    eventTagline: 'La finca también se presta a sus grandes momentos: bodas campestres, seminarios de empresa, recepciones privadas o comidas familiares.',
    eventParagraph: 'Sala de recepciones, terraza y parque de la finca, la cocina de nuestro restaurante y las casas rurales para alojar a los invitados: diseñamos cada evento a medida, desde un cóctel en el parque hasta una cena sentada para cien invitados.',
    eventCta: 'SOLICITAR PRESUPUESTO',
    restEyebrow: 'GASTRONOMÍA DE TERRUÑO', restTitle: 'El Restaurante', restTagline: 'Una cocina de temporada, arraigada en el terruño de la finca.',
    menuEyebrow: 'LA CARTA', menuTitle: 'El Menú',
    menuTerroirTitle: 'Menú Terruño', menuTerroirSub: 'Entrante · Plato · Postre',
    menuEstreeTitle: 'Menú Signature', menuEstreeSub: 'Degustación en seis tiempos, maridaje de vinos',
    galleryEyebrow: 'GALERÍA', galleryTitle: 'La mesa, la sala, el ambiente',
    hoursEyebrow: 'HORARIOS', hoursText: 'De miércoles a domingo', hoursLunch: 'Comida · 12:00 – 13:30 h', hoursDinner: 'Cena · 19:30 – 21:30 h', hoursClosed: 'Cerrado lunes y martes',
    cuisineEyebrow: 'LA COCINA', cuisineText: 'Gastronómica · Terruño', cuisineText2: 'Productos de la finca y de productores vecinos', cuisineText3: 'Carta renovada cada temporada',
    resaEyebrow: 'RESERVAS', resaText: 'Solo por teléfono',
    aemporterEyebrow: 'PARA LLEVAR', aemporterTitle: 'Para Llevar', aemporterTagline: 'La cocina del restaurante, para disfrutar en casa.',
    aemporterParagraph: 'Platos cocinados a fuego lento, entrantes y postres preparados por nuestra cocina, listos para recoger. La carta cambia según la temporada y el mercado — llámenos para conocer los platos del día.',
    aemporterHoursText: 'Recogida de miércoles a domingo', aemporterHoursLunch: '12:00 – 13:30 h', aemporterHoursDinner: '19:00 – 20:30 h',
    aemporterOrderEyebrow: 'PEDIDOS', aemporterOrderText: 'Por teléfono, preferiblemente el día anterior', aemporterCta: 'LLAMAR PARA PEDIR',
    gitesEyebrow: 'ALOJARSE EN LA FINCA', gitesTitle: 'Las Casas Rurales',
    gitesTagline: 'Cuatro casas restauradas con esmero, repartidas por el parque de la finca. Cada una tiene su carácter; todas comparten el mismo gusto por la calma y los materiales nobles.',
    gitesDetail1: 'Detalle 1', gitesDetail2: 'Detalle 2', gitesDetail3: 'Detalle 3',
    gitesCtaTitle: '¿Le apetece alojarse en la finca?', gitesCtaText: 'Las casas rurales se reservan fácilmente, por teléfono o por escrito. Diseñaremos su estancia junto a usted.',
    spaEyebrow: 'SILENCIO · CALOR · AGUA', spaTitle: 'El Spa', spaTagline: 'Un espacio cerrado y aterciopelado, reservado a los huéspedes de la finca.',
    practiceEyebrow: 'INFORMACIÓN PRÁCTICA', practiceTitle: 'Acceso al spa',
    practice1Title: 'Abierto todos los días', practice1Text: '10:00 – 20:00 h, en franjas privatizadas',
    practice2Title: 'Reservado a los huéspedes', practice2Text: 'Incluido en las estancias en casa rural, bajo petición en el restaurante',
    practice3Title: 'Ropa de baño incluida', practice3Text: 'Albornoces, toallas y zapatillas a su disposición',
    ctaBookSlot: 'RESERVAR UNA FRANJA',
    contactEyebrow: 'CONTACTO', contactTitle1: 'Escríbanos,', contactTitle2: 'o venga a vernos.',
    addressLabel: 'DIRECCIÓN', phoneLabel: 'TELÉFONO', emailLabel: 'CORREO ELECTRÓNICO',
    contactHours: 'Recepción de lunes a domingo, 9 – 19 h.', contactHours2: 'Restaurante, casas rurales y spa: toda solicitud por teléfono o correo electrónico — respondemos en 24 h.',
    formNameLabel: 'APELLIDO', formFirstNameLabel: 'NOMBRE', formEmailLabel: 'CORREO ELECTRÓNICO', formMessageLabel: 'MENSAJE',
    formNamePh: 'Su apellido', formFirstNamePh: 'Su nombre', formEmailPh: 'usted@ejemplo.com', formMessagePh: 'Su mensaje…',
    formSendBtn: 'ENVIAR MENSAJE', formNote: 'Al hacer clic en enviar, se abrirá su aplicación de correo con este mensaje ya redactado.',
    recruitEyebrow: 'ÚNASE A NOSOTROS', recruitTitle: 'Empleo', recruitTagline: 'Le Méandre crece con las personas que trabajan aquí.',
    recruitParagraph: 'Contratamos regularmente en cocina, en sala y para el mantenimiento de la finca y las casas rurales. ¿Ningún puesto abierto le corresponde hoy? Envíenos una candidatura espontánea: guardamos cada currículum y le contactamos en cuanto se abra un puesto.',
    recruitCta: 'ENVIAR MI CANDIDATURA', recruitEmailNote: 'CV y carta de motivación a:',
    sinceWord: 'DESDE',
    phHero: 'Foto de la finca — vista exterior, gran formato', phAccRest: 'Plato signature', phAccGites: 'Interior de una casa rural', phAccSpa: 'Piscina cubierta / spa',
    phRestHero: 'Sala del restaurante o plato — banner ancho', phSpaHero: 'Piscina cubierta — gran formato inmersivo', phContact: 'Foto — camino de acceso, portón o plano de acceso',
    phAEmporter: 'Platos para llevar — envase o plato del día'
  },
  nl: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'AFHALEN', navGites: 'GÎTES', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'VACATURES',
    heroTagline: 'Gastronomisch restaurant, karaktervolle gîtes en een spa — een levenskunst in het hart van de Sept Vallées.',
    cardRestTitle: 'Het Restaurant', cardRestDesc: 'Een gastronomische, seizoensgebonden keuken, geworteld in het terroir.',
    cardGitesTitle: 'De Gîtes', cardGitesDesc: 'Vier karaktervolle huizen om het verblijf te verlengen.',
    cardSpaTitle: 'De Spa', cardSpaDesc: 'Hammam, sauna en binnenzwembad, in volstrekte rust.',
    discover: 'ONTDEKKEN →',
    artEyebrow: 'DE KUNST VAN GASTVRIJHEID', artTitle1: 'Een familiedomein waar elk verblijf', artTitle2: 'aanvoelt als een adempauze.',
    artParagraph: 'Tussen vijvers en bossen cultiveert dit familiedomein al vijf generaties lang een discrete gastvrijheid: een veeleisende keuken, huizen vol ziel en een spa gewijd aan rust.',
    ctaContact: 'NEEM CONTACT OP',
    eventEyebrow: 'SEMINARS · BRUILOFTEN · RECEPTIES', eventTitle: 'Evenementen',
    eventTagline: 'Het domein leent zich ook voor uw bijzondere momenten: landelijke bruiloften, bedrijfsseminars, privérecepties of familiediners.',
    eventParagraph: 'Ontvangstzaal, terras en park van het domein, de keuken van ons restaurant en de gîtes voor de overnachting van gasten: wij stellen elk evenement op maat samen, van een cocktail in het park tot een zittend diner voor honderd gasten.',
    eventCta: 'OFFERTE AANVRAGEN',
    restEyebrow: 'STREEKGASTRONOMIE', restTitle: 'Het Restaurant', restTagline: 'Een seizoensgebonden keuken, geworteld in het terroir van het domein.',
    menuEyebrow: 'DE KAART', menuTitle: 'Het Menu',
    menuTerroirTitle: 'Menu Terroir', menuTerroirSub: 'Voorgerecht · Hoofdgerecht · Dessert',
    menuEstreeTitle: 'Signature Menu', menuEstreeSub: 'Zesgangen proeverij, met wijnbegeleiding',
    galleryEyebrow: 'IN BEELD', galleryTitle: 'De tafel, de zaal, de sfeer',
    hoursEyebrow: 'OPENINGSTIJDEN', hoursText: 'Woensdag tot en met zondag', hoursLunch: 'Lunch · 12:00 – 13:30 uur', hoursDinner: 'Diner · 19:30 – 21:30 uur', hoursClosed: 'Gesloten op maandag en dinsdag',
    cuisineEyebrow: 'DE KEUKEN', cuisineText: 'Gastronomisch · Terroir', cuisineText2: 'Producten van het domein en van naburige producenten', cuisineText3: 'Kaart elk seizoen vernieuwd',
    resaEyebrow: 'RESERVERING', resaText: 'Uitsluitend telefonisch',
    aemporterEyebrow: 'AFHALEN', aemporterTitle: 'Afhaalgerechten', aemporterTagline: 'De keuken van het restaurant, thuis te genieten.',
    aemporterParagraph: 'Stoofgerechten, voorgerechten en desserts bereid door onze keuken, klaar om af te halen. De kaart verandert met het seizoen en het aanbod — bel ons voor de gerechten van de dag.',
    aemporterHoursText: 'Afhalen van woensdag tot zondag', aemporterHoursLunch: '12:00 – 13:30 uur', aemporterHoursDinner: '19:00 – 20:30 uur',
    aemporterOrderEyebrow: 'BESTELLEN', aemporterOrderText: 'Telefonisch, bij voorkeur de dag ervoor', aemporterCta: 'BEL OM TE BESTELLEN',
    gitesEyebrow: 'VERBLIJVEN OP HET DOMEIN', gitesTitle: 'De Gîtes',
    gitesTagline: 'Vier zorgvuldig gerestaureerde huizen, verspreid over het park van het domein. Elk heeft zijn eigen karakter; allemaal delen ze dezelfde smaak voor rust en materiaal.',
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Zin om op het domein te verblijven?', gitesCtaText: 'De gîtes worden eenvoudig geboekt, telefonisch of schriftelijk. Wij stellen uw verblijf samen met u samen.',
    spaEyebrow: 'STILTE · WARMTE · WATER', spaTitle: 'De Spa', spaTagline: 'Een besloten, gedempte plek, voorbehouden aan de gasten van het domein.',
    practiceEyebrow: 'PRAKTISCHE INFORMATIE', practiceTitle: 'Toegang tot de spa',
    practice1Title: 'Elke dag geopend', practice1Text: '10:00 – 20:00 uur, in geprivatiseerde tijdsloten',
    practice2Title: 'Voorbehouden aan gasten', practice2Text: 'Inbegrepen bij een verblijf in een gîte, op aanvraag bij het restaurant',
    practice3Title: 'Linnengoed inbegrepen', practice3Text: 'Badjassen, handdoeken en slippers ter beschikking',
    ctaBookSlot: 'TIJDSLOT BOEKEN',
    contactEyebrow: 'CONTACT', contactTitle1: 'Schrijf ons,', contactTitle2: 'of kom langs.',
    addressLabel: 'ADRES', phoneLabel: 'TELEFOON', emailLabel: 'E-MAIL',
    contactHours: 'Onthaal van maandag tot zondag, 9 – 19 uur.', contactHours2: 'Restaurant, gîtes en spa: alle aanvragen telefonisch of per e-mail — wij reageren binnen 24 uur.',
    formNameLabel: 'ACHTERNAAM', formFirstNameLabel: 'VOORNAAM', formEmailLabel: 'E-MAIL', formMessageLabel: 'BERICHT',
    formNamePh: 'Uw achternaam', formFirstNamePh: 'Uw voornaam', formEmailPh: 'u@voorbeeld.com', formMessagePh: 'Uw bericht…',
    formSendBtn: 'BERICHT VERSTUREN', formNote: 'Als u op verzenden klikt, wordt uw e-mailprogramma geopend met dit vooraf ingevulde bericht.',
    recruitEyebrow: 'KOM BIJ ONS WERKEN', recruitTitle: 'Vacatures', recruitTagline: 'Le Méandre groeit met de mensen die hier werken.',
    recruitParagraph: 'Wij werven regelmatig personeel voor de keuken, de bediening en het onderhoud van het domein en de gîtes. Niets vrij dat bij u past? Stuur ons een open sollicitatie: wij bewaren elk cv en nemen contact op zodra er een functie vrijkomt.',
    recruitCta: 'MIJN SOLLICITATIE VERSTUREN', recruitEmailNote: 'Cv en motivatiebrief naar:',
    sinceWord: 'SINDS',
    phHero: 'Foto van het domein — buitenaanzicht, groot formaat', phAccRest: 'Signature gerecht', phAccGites: 'Interieur van een gîte', phAccSpa: 'Binnenzwembad / spa',
    phRestHero: 'Eetzaal of gerecht — brede banner', phSpaHero: 'Binnenzwembad — groot immersief formaat', phContact: 'Foto — oprijlaan, poort of toegangsplan',
    phAEmporter: 'Afhaalgerechten — verpakking of dagschotel'
  }
};

// ── Carte du restaurant (3 catégories × 3 plats) ──
window.MEANDRE_MENU = [
  { nom: { fr: 'Entrées', en: 'Starters', de: 'Vorspeisen', es: 'Entrantes', nl: 'Voorgerechten' }, plats: [
    { nom: { fr: 'Velouté de topinambour', en: 'Jerusalem artichoke velouté', de: 'Topinambur-Velouté', es: 'Velouté de topinambo', nl: 'Topinamboer-veloutésoep' }, desc: { fr: 'Noisettes torréfiées, huile de livèche', en: 'Toasted hazelnuts, lovage oil', de: 'Geröstete Haselnüsse, Liebstocköl', es: 'Avellanas tostadas, aceite de levístico', nl: 'Gebrande hazelnoten, lavasolie' }, prix: '18 €' },
    { nom: { fr: 'Foie gras de canard mi-cuit', en: 'Duck foie gras, mi-cuit', de: 'Entenfoie gras, mi-cuit', es: 'Foie gras de pato, mi-cuit', nl: 'Eendenfoie gras, mi-cuit' }, desc: { fr: 'Chutney de figues du verger, brioche toastée', en: 'Orchard fig chutney, toasted brioche', de: 'Feigenchutney aus dem Obstgarten, geröstete Brioche', es: 'Chutney de higos del huerto, brioche tostada', nl: 'Vijgenchutney uit de boomgaard, geroosterde brioche' }, prix: '24 €' },
    { nom: { fr: 'Tartare de truite', en: 'Trout tartare', de: 'Forellentatar', es: 'Tartar de trucha', nl: 'Forellentartaar' }, desc: { fr: "Crème d'aneth, pickles d'oignon rouge", en: 'Dill cream, pickled red onion', de: 'Dillcreme, eingelegte rote Zwiebeln', es: 'Crema de eneldo, encurtido de cebolla roja', nl: 'Dilroom, ingelegde rode ui' }, prix: '21 €' }] },
  { nom: { fr: 'Plats', en: 'Mains', de: 'Hauptgerichte', es: 'Platos principales', nl: 'Hoofdgerechten' }, plats: [
    { nom: { fr: 'Filet de bœuf des pâtures', en: 'Pasture-raised beef fillet', de: 'Rinderfilet von der Weide', es: 'Solomillo de ternera de pasto', nl: 'Runderfilet van de weide' }, desc: { fr: 'Jus corsé au vin rouge, légumes racines confits', en: 'Red wine jus, confit root vegetables', de: 'Kräftiger Rotweinjus, confierte Wurzelgemüse', es: 'Jugo intenso al vino tinto, verduras de raíz confitadas', nl: 'Krachtige rodewijnjus, geconfijte wortelgroenten' }, prix: '42 €' },
    { nom: { fr: 'Sandre rôti sur peau', en: 'Pan-roasted zander, crispy skin', de: 'Gebratener Zander mit knuspriger Haut', es: 'Lucioperca asada con piel crujiente', nl: 'Gebakken snoekbaars, krokante huid' }, desc: { fr: 'Beurre blanc au safran, poireaux brûlés', en: 'Saffron beurre blanc, charred leeks', de: 'Safran-Beurre-blanc, geröstete Lauch', es: 'Beurre blanc al azafrán, puerros tostados', nl: 'Saffraan-beurre-blanc, geschroeide prei' }, prix: '38 €' },
    { nom: { fr: 'Pigeon fermier en deux cuissons', en: 'Farmhouse pigeon, two ways', de: 'Bauernhof-Taube, zweifach gegart', es: 'Pichón de granja en dos cocciones', nl: 'Boerderijduif op twee bereidingswijzen' }, desc: { fr: 'Cerises acidulées, polenta crémeuse', en: 'Tart cherries, creamy polenta', de: 'Säuerliche Kirschen, cremige Polenta', es: 'Cerezas ácidas, polenta cremosa', nl: 'Zurige kersen, romige polenta' }, prix: '44 €' }] },
  { nom: { fr: 'Desserts', en: 'Desserts', de: 'Desserts', es: 'Postres', nl: 'Desserts' }, plats: [
    { nom: { fr: 'Soufflé chaud au Grand Marnier', en: 'Warm Grand Marnier soufflé', de: 'Warmes Grand-Marnier-Soufflé', es: 'Suflé caliente de Grand Marnier', nl: 'Warme Grand Marnier-soufflé' }, desc: { fr: 'Minute, pour deux personnes', en: 'Made to order, for two', de: 'Frisch zubereitet, für zwei Personen', es: 'Al momento, para dos personas', nl: 'Op het moment bereid, voor twee personen' }, prix: '16 €' },
    { nom: { fr: 'Tarte fine aux poires', en: 'Thin pear tart', de: 'Feine Birnentarte', es: 'Tarta fina de peras', nl: 'Fijne perentaart' }, desc: { fr: 'Glace miel-lavande du domaine', en: 'Estate honey-lavender ice cream', de: 'Honig-Lavendel-Eis vom Anwesen', es: 'Helado de miel y lavanda de la finca', nl: 'Honing-lavendelijs van het domein' }, prix: '14 €' },
    { nom: { fr: 'Sphère chocolat grand cru', en: 'Grand cru chocolate sphere', de: 'Grand-Cru-Schokoladenkugel', es: 'Esfera de chocolate grand cru', nl: 'Grand cru chocoladebol' }, desc: { fr: "Cœur caramel, feuille d'or", en: 'Caramel heart, gold leaf', de: 'Karamellkern, Blattgold', es: 'Corazón de caramelo, pan de oro', nl: 'Karamelhart, bladgoud' }, prix: '17 €' }] }
];

// ── Les 4 gîtes ── (slotA-D sont les clés de persistance des photos déposées
// dans chaque image-slot — ne pas les modifier sans mettre à jour le gabarit)
window.MEANDRE_GITES = [
  { num: '01',
    nom: { fr: 'Le Pressoir', en: 'The Press House', de: 'Die Kelter', es: 'El Lagar', nl: 'De Perserij' },
    capacite: { fr: '2 – 4 PERSONNES · 68 M²', en: '2–4 GUESTS · 68 M²', de: '2–4 PERSONEN · 68 M²', es: '2 – 4 PERSONAS · 68 M²', nl: '2–4 PERSONEN · 68 M²' },
    desc: { fr: "L'ancien pressoir du domaine, ouvert sur le verger. Pierres apparentes, poutres d'origine et cheminée pour les soirées d'hiver.", en: "The estate's former press house, opening onto the orchard. Exposed stone, original beams and a fireplace for winter evenings.", de: 'Die ehemalige Kelter des Anwesens, zum Obstgarten hin geöffnet. Freiliegendes Mauerwerk, Originalbalken und ein Kamin für Winterabende.', es: 'El antiguo lagar de la finca, abierto al huerto. Piedra vista, vigas originales y chimenea para las noches de invierno.', nl: 'De voormalige perserij van het domein, met uitzicht op de boomgaard. Zichtbaar steenwerk, originele balken en een open haard voor winteravonden.' },
    equip: { fr: ['Cheminée', 'Cuisine équipée', 'Terrasse privée', 'Linge fourni'], en: ['Fireplace', 'Equipped kitchen', 'Private terrace', 'Linens provided'], de: ['Kamin', 'Ausgestattete Küche', 'Private Terrasse', 'Wäsche gestellt'], es: ['Chimenea', 'Cocina equipada', 'Terraza privada', 'Ropa de cama incluida'], nl: ['Open haard', 'Volledig uitgeruste keuken', 'Privéterras', 'Linnengoed inbegrepen'] },
    slotA: 'site-g1a', slotB: 'site-g1b', slotC: 'site-g1c', slotD: 'site-g1d', srcA: './images/gite1_1.JPG',
    phA: { fr: 'Le Pressoir — pièce principale', en: 'The Press House — main room', de: 'Die Kelter — Hauptraum', es: 'El Lagar — sala principal', nl: 'De Perserij — hoofdkamer' } },
  { num: '02',
    nom: { fr: 'La Grange', en: 'The Barn', de: 'Die Scheune', es: 'El Granero', nl: 'De Schuur' },
    capacite: { fr: '4 – 6 PERSONNES · 110 M²', en: '4–6 GUESTS · 110 M²', de: '4–6 PERSONEN · 110 M²', es: '4 – 6 PERSONAS · 110 M²', nl: '4–6 PERSONEN · 110 M²' },
    desc: { fr: 'La plus vaste des maisons : une grande pièce à vivre sous charpente, trois chambres et une vue dégagée sur les étangs.', en: 'The largest of the houses: a vast living space under exposed timber framing, three bedrooms and open views over the ponds.', de: 'Das größte der Häuser: ein großer Wohnraum unter freiliegendem Dachstuhl, drei Schlafzimmer und ein weiter Blick auf die Teiche.', es: 'La más amplia de las casas: un gran espacio de vida bajo el entramado de madera, tres dormitorios y una vista despejada sobre los estanques.', nl: 'Het grootste van de huizen: een grote woonruimte onder een open dakconstructie, drie slaapkamers en een vrij uitzicht over de vijvers.' },
    equip: { fr: ['3 chambres', 'Poêle à bois', "Grande table d'hôte", 'Jardin clos'], en: ['3 bedrooms', 'Wood stove', 'Large communal table', 'Walled garden'], de: ['3 Schlafzimmer', 'Holzofen', 'Große Tafel', 'Umfriedeter Garten'], es: ['3 dormitorios', 'Estufa de leña', 'Gran mesa comunal', 'Jardín cerrado'], nl: ['3 slaapkamers', 'Houtkachel', 'Grote gemeenschappelijke tafel', 'Omheinde tuin'] },
    slotA: 'site-g2a', slotB: 'site-g2b', slotC: 'site-g2c', slotD: 'site-g2d', srcA: './images/gite2_1.JPG', srcB: './images/gite2_2.JPG',
    phA: { fr: 'La Grange — pièce à vivre', en: 'The Barn — living area', de: 'Die Scheune — Wohnbereich', es: 'El Granero — sala de estar', nl: 'De Schuur — woonruimte' } },
  { num: '03',
    nom: { fr: 'Le Pigeonnier', en: 'The Dovecote', de: 'Der Taubenschlag', es: 'El Palomar', nl: 'De Duiventoren' },
    capacite: { fr: '2 PERSONNES · 42 M²', en: '2 GUESTS · 42 M²', de: '2 PERSONEN · 42 M²', es: '2 PERSONAS · 42 M²', nl: '2 PERSONEN · 42 M²' },
    desc: { fr: 'Un refuge pour deux, sur trois demi-niveaux. La chambre perchée regarde la cime des arbres — idéal pour une échappée.', en: 'A hideaway for two, spread across three split levels. The perched bedroom looks out over the treetops — perfect for a getaway.', de: 'Ein Rückzugsort für zwei, auf drei Splitlevel-Ebenen. Das erhöhte Schlafzimmer blickt auf die Baumwipfel — ideal für eine Auszeit.', es: 'Un refugio para dos, en tres medios niveles. El dormitorio elevado mira hacia las copas de los árboles — ideal para una escapada.', nl: 'Een toevluchtsoord voor twee, verdeeld over drie halve verdiepingen. De verheven slaapkamer kijkt uit over de boomtoppen — ideaal voor een uitje.' },
    equip: { fr: ['Lit king size', 'Baignoire îlot', 'Petit-déjeuner porté', 'Vue sur le parc'], en: ['King-size bed', 'Freestanding bathtub', 'Breakfast delivered', 'Park view'], de: ['Kingsize-Bett', 'Freistehende Badewanne', 'Frühstück serviert', 'Blick auf den Park'], es: ['Cama king size', 'Bañera exenta', 'Desayuno servido', 'Vistas al parque'], nl: ['Kingsize bed', 'Vrijstaand bad', 'Ontbijt aan huis', 'Uitzicht op het park'] },
    slotA: 'site-g3a', slotB: 'site-g3b', slotC: 'site-g3c', slotD: 'site-g3d', srcA: './images/gite3_1.JPG', srcB: './images/gite3_2.JPG',
    phA: { fr: 'Le Pigeonnier — chambre perchée', en: 'The Dovecote — perched bedroom', de: 'Der Taubenschlag — erhöhtes Schlafzimmer', es: 'El Palomar — dormitorio elevado', nl: 'De Duiventoren — verheven slaapkamer' } },
  { num: '04',
    nom: { fr: 'La Métairie', en: 'The Farmhouse', de: 'Der Pachthof', es: 'La Alquería', nl: 'De Pachthoeve' },
    capacite: { fr: '6 – 8 PERSONNES · 145 M²', en: '6–8 GUESTS · 145 M²', de: '6–8 PERSONEN · 145 M²', es: '6 – 8 PERSONAS · 145 M²', nl: '6–8 PERSONEN · 145 M²' },
    desc: { fr: 'La maison de famille par excellence : quatre chambres, une cuisine généreuse et une longue terrasse orientée couchant.', en: 'The quintessential family house: four bedrooms, a generous kitchen and a long west-facing terrace.', de: 'Das Familienhaus schlechthin: vier Schlafzimmer, eine großzügige Küche und eine lange, nach Westen ausgerichtete Terrasse.', es: 'La casa familiar por excelencia: cuatro dormitorios, una cocina generosa y una larga terraza orientada al poniente.', nl: 'Het familiehuis bij uitstek: vier slaapkamers, een royale keuken en een lang, westgericht terras.' },
    equip: { fr: ['4 chambres', '2 salles de bain', 'Terrasse 40 m²', 'Accès spa inclus'], en: ['4 bedrooms', '2 bathrooms', '40 m² terrace', 'Spa access included'], de: ['4 Schlafzimmer', '2 Badezimmer', 'Terrasse 40 m²', 'Spa-Zugang inklusive'], es: ['4 dormitorios', '2 baños', 'Terraza de 40 m²', 'Acceso al spa incluido'], nl: ['4 slaapkamers', '2 badkamers', 'Terras van 40 m²', 'Spatoegang inbegrepen'] },
    slotA: 'site-g4a', slotB: 'site-g4b', slotC: 'site-g4c', slotD: 'site-g4d', srcA: './images/gite4_1.JPG', srcB: './images/gite4_2.JPG',
    phA: { fr: 'La Métairie — façade ou terrasse', en: 'The Farmhouse — façade or terrace', de: 'Der Pachthof — Fassade oder Terrasse', es: 'La Alquería — fachada o terraza', nl: 'De Pachthoeve — gevel of terras' } }
];

// ── Les 3 espaces du spa ── (slot = clé de persistance de la photo déposée)
window.MEANDRE_SPAS = [
  { nom: { fr: 'La Piscine intérieure', en: 'The Indoor Pool', de: 'Der Innenpool', es: 'La Piscina Interior', nl: 'Het Binnenzwembad' },
    sur: { fr: 'BASSIN · 28°C', en: 'POOL · 82°F', de: 'BECKEN · 28°C', es: 'PISCINA · 28°C', nl: 'BAD · 28°C' },
    desc: { fr: "Un bassin de nage de quinze mètres sous verrière, chauffé toute l'année. La lumière du parc entre à travers les arbres ; on n'entend que l'eau.", en: 'A fifteen-metre lap pool beneath a glass roof, heated year-round. Light from the park filters through the trees; all you hear is the water.', de: 'Ein fünfzehn Meter langes Schwimmbecken unter einem Glasdach, ganzjährig beheizt. Das Licht des Parks fällt durch die Bäume; man hört nur das Wasser.', es: 'Una piscina de natación de quince metros bajo una cristalera, climatizada todo el año. La luz del parque se filtra entre los árboles; solo se oye el agua.', nl: 'Een vijftien meter lang zwembad onder een glazen overkapping, het hele jaar verwarmd. Het licht van het park valt door de bomen; je hoort alleen het water.' },
    info: { fr: 'Longueur 15 m · Profondeur 1,40 m', en: 'Length 15 m · Depth 1.4 m', de: 'Länge 15 m · Tiefe 1,40 m', es: 'Longitud 15 m · Profundidad 1,40 m', nl: 'Lengte 15 m · Diepte 1,40 m' },
    slot: 'site-spa-piscine', src: '', ph: { fr: 'Piscine intérieure', en: 'Indoor pool', de: 'Innenpool', es: 'Piscina interior', nl: 'Binnenzwembad' }, dir: 'ltr' },
  { nom: { fr: 'Le Hammam', en: 'The Hammam', de: 'Das Hammam', es: 'El Hammam', nl: 'De Hamam' },
    sur: { fr: 'VAPEUR · EUCALYPTUS', en: 'STEAM · EUCALYPTUS', de: 'DAMPF · EUKALYPTUS', es: 'VAPOR · EUCALIPTO', nl: 'STOOM · EUCALYPTUS' },
    desc: { fr: "Marbre sombre, vapeur d'eucalyptus et banquettes chauffées. Une chaleur humide et enveloppante, à vivre lentement.", en: 'Dark marble, eucalyptus steam and heated benches. An enveloping, humid warmth, best savoured slowly.', de: 'Dunkler Marmor, Eukalyptusdampf und beheizte Sitzbänke. Eine feuchte, umhüllende Wärme, die man langsam genießen sollte.', es: 'Mármol oscuro, vapor de eucalipto y banquetas climatizadas. Un calor húmedo y envolvente, para vivir despacio.', nl: 'Donker marmer, eucalyptusstoom en verwarmde banken. Een vochtige, omhullende warmte, langzaam te beleven.' },
    info: { fr: "45°C · 100 % d'humidité", en: '113°F · 100% humidity', de: '45°C · 100 % Luftfeuchtigkeit', es: '45°C · 100 % de humedad', nl: '45°C · 100% luchtvochtigheid' },
    slot: 'site-spa-hammam', src: '', ph: { fr: 'Hammam — marbre et vapeur', en: 'Hammam — marble and steam', de: 'Hammam — Marmor und Dampf', es: 'Hammam — mármol y vapor', nl: 'Hamam — marmer en stoom' }, dir: 'rtl' },
  { nom: { fr: 'Le Sauna', en: 'The Sauna', de: 'Die Sauna', es: 'La Sauna', nl: 'De Sauna' },
    sur: { fr: 'BOIS · CHALEUR SÈCHE', en: 'WOOD · DRY HEAT', de: 'HOLZ · TROCKENE HITZE', es: 'MADERA · CALOR SECO', nl: 'HOUT · DROGE WARMTE' },
    desc: { fr: 'Un sauna finlandais en épicéa, donnant sur le sous-bois. Chaleur sèche, silence, et une douche froide en sortie pour relancer le corps.', en: 'A Finnish spruce sauna overlooking the woods. Dry heat, silence, and a cold shower on the way out to revive the body.', de: 'Eine finnische Sauna aus Fichtenholz mit Blick auf das Unterholz. Trockene Hitze, Stille, und eine kalte Dusche zum Abschluss, um den Kreislauf anzuregen.', es: 'Una sauna finlandesa de abeto, con vistas al sotobosque. Calor seco, silencio, y una ducha fría a la salida para reactivar el cuerpo.', nl: 'Een Finse sauna van sparrenhout, met uitzicht op het kreupelhout. Droge warmte, stilte, en een koude douche bij het verlaten om het lichaam te verkwikken.' },
    info: { fr: '85°C · Séances de 15 min', en: '185°F · 15-min sessions', de: '85°C · 15-minütige Sitzungen', es: '85°C · Sesiones de 15 min', nl: '85°C · Sessies van 15 min' },
    slot: 'site-spa-sauna', src: '', ph: { fr: 'Sauna — bois clair', en: 'Sauna — pale wood', de: 'Sauna — helles Holz', es: 'Sauna — madera clara', nl: 'Sauna — licht hout' }, dir: 'ltr' }
];

// ── Réservoir de légendes pour le carrousel photo du restaurant ──
// (nbPhotosCarrousel, une prop éditable, détermine combien d'entre elles sont utilisées)
window.MEANDRE_POOL = [
  { slot: 'site-car-1', src: './images/restaurant1.JPEG', ph: { fr: 'Photo 1 — plat', en: 'Photo 1 — dish', de: 'Foto 1 — Gericht', es: 'Foto 1 — plato', nl: 'Foto 1 — gerecht' } },
  { slot: 'site-car-2', src: './images/restaurant2.JPEG', ph: { fr: 'Photo 2 — salle', en: 'Photo 2 — dining room', de: 'Foto 2 — Speisesaal', es: 'Foto 2 — sala', nl: 'Foto 2 — eetzaal' } },
  { slot: 'site-car-3', ph: { fr: 'Photo 3 — ambiance', en: 'Photo 3 — atmosphere', de: 'Foto 3 — Atmosphäre', es: 'Foto 3 — ambiente', nl: 'Foto 3 — sfeer' } },
  { slot: 'site-car-4', ph: { fr: 'Photo 4 — dessert', en: 'Photo 4 — dessert', de: 'Foto 4 — Dessert', es: 'Foto 4 — postre', nl: 'Foto 4 — dessert' } },
  { slot: 'site-car-5', ph: { fr: 'Photo 5 — terrasse', en: 'Photo 5 — terrace', de: 'Foto 5 — Terrasse', es: 'Foto 5 — terraza', nl: 'Foto 5 — terras' } },
  { slot: 'site-car-6', ph: { fr: 'Photo 6 — cave', en: 'Photo 6 — cellar', de: 'Foto 6 — Weinkeller', es: 'Foto 6 — bodega', nl: 'Foto 6 — kelder' } },
  { slot: 'site-car-7', ph: { fr: 'Photo 7 — cuisine', en: 'Photo 7 — kitchen', de: 'Foto 7 — Küche', es: 'Foto 7 — cocina', nl: 'Foto 7 — keuken' } },
  { slot: 'site-car-8', ph: { fr: 'Photo 8 — détail', en: 'Photo 8 — detail', de: 'Foto 8 — Detail', es: 'Foto 8 — detalle', nl: 'Foto 8 — detail' } }
];

// ── Recrutement : postes ouverts (liste vide = candidatures spontanées uniquement) ──
window.MEANDRE_JOBS = [];
