// Le Méandre — textes de l'interface (nav, en-têtes, appels à l'action,
// légendes), FR/EN/DE/ES/NL. Chargé avant index.html ; lu par
// Component._localizedContent() (index.html) via window.MEANDRE_UI[lang].
// Fichier à modifier pour changer un texte ou ajouter une traduction —
// pour un plat, un gîte, le spa ou l'agenda, voir site-data-content.js.
window.MEANDRE_UI = {
  fr: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'À EMPORTER', navGites: 'LE GÎTE', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'RECRUTEMENT', footerScene: 'SCÈNE & ART',
    heroTagline: "Restaurant, gîte et spa dans un ancien relais chargé d'histoire, au cœur de la Vallée de la Course.",
    cardRestTitle: 'Le Restaurant', cardRestDesc: 'Une cuisine raffinée entre terre et mer, au fil des saisons.',
    cardGitesTitle: 'Le Gîte', cardGitesDesc: "Quatre chambres indépendantes, à réserver séparément, au sein d'une même maison.",
    cardSpaTitle: 'Le Spa', cardSpaDesc: 'Un spa, dans une quiétude absolue.',
    discover: 'DÉCOUVRIR →',
    artEyebrow: 'ESTRÉE · VALLÉE DE LA COURSE', artTitle1: 'Bienvenue', artTitle2: 'au Méandre',
    artPara1: "Au cœur de la Vallée de la Course, à Estrée, Le Méandre vous accueille dans un lieu chargé d'histoire, où l'art de recevoir se transmet depuis plusieurs années.",
    artPara2: "Ancien relais et adresse dédiée à l'accueil des voyageurs, la maison a connu plusieurs vies avant d'écrire aujourd'hui un nouveau chapitre sous le nom du Méandre.",
    artPara3: "Notre établissement associe restaurant, gîte et spa, dans un esprit chaleureux et raffiné.",
    artCuisineTitle: "Une cuisine raffinée, entre terre et mer, au fil des saisons",
    artPara4: "Au restaurant, nous défendons une cuisine gourmande, élégante et de saison, inspirée par notre terroir et la proximité de la Côte d'Opale. Les produits de la mer y tiennent une place privilégiée, accompagnés de produits locaux et de belles inspirations culinaires.",
    artPara5: "Notre ambition : vous offrir une table d'exception, dans un cadre où l'on prend le temps de partager, de découvrir et de profiter.",
    artPara6: "Le Méandre, c'est une nouvelle histoire qui s'écrit au fil de la Course.",
    artTagline: "Restaurant · Gîte · Spa",
    ctaContact: 'NOUS CONTACTER',
    eventEyebrow: 'SÉMINAIRES · MARIAGES · RÉCEPTIONS', eventTitle: "L'Événementiel",
    eventTagline: "Le relais se prête aussi à vos temps forts : mariages, séminaires d'entreprise, réceptions privées ou repas de famille.",
    eventParagraph: "Salle de réception, terrasse, jardin et salon privé, cuisine du restaurant et gîte pour l'hébergement des invités : nous composons chaque événement sur mesure, du cocktail au jardin au dîner dans notre salon privé.",
    eventCta: 'DEMANDER UN DEVIS',
    restTitle: 'Le Restaurant',
    menuEyebrow: 'LA CARTE', menuTitle: 'Le Menu',
    menuTerroirTitle: 'Menu Terroir', menuTerroirSub: 'Entrée · Plat · Dessert',
    menuEstreeTitle: 'Menu Signature', menuEstreeSub: 'Dégustation en six temps, accords mets & vins',
    galleryEyebrow: 'EN IMAGES', galleryTitle: "La table, la salle, l'ambiance",
    hoursEyebrow: 'HORAIRES', hoursText: 'Du mercredi au dimanche', hoursLunch: 'Déjeuner · 12h00 – 13h30', hoursDinner: 'Dîner · 19h30 – 21h30', hoursClosed: 'Fermé lundi et mardi',
    cuisineEyebrow: 'LA CUISINE', cuisineText: 'Raffinée · Terre et Mer', cuisineText2: 'Produits de la mer et producteurs locaux', cuisineText3: 'Carte renouvelée à chaque saison',
    resaEyebrow: 'RÉSERVATION', resaText: 'Par téléphone uniquement',
    accessEyebrow: 'ACCÈS', accessMapCta: 'Voir l’itinéraire sur Google Maps →',
    aemporterEyebrow: 'À EMPORTER', aemporterTitle: 'La Table à Emporter', aemporterTagline: 'La cuisine du restaurant, à savourer chez vous.',
    aemporterParagraph: 'Plats mijotés, entrées et desserts préparés par notre cuisine, à récupérer sur place. La carte change selon la saison et les arrivages — appelez-nous pour connaître les plats du jour.',
    aemporterHoursText: 'Retrait du mercredi au dimanche', aemporterHoursLunch: '12h00 – 13h30', aemporterHoursDinner: '19h00 – 20h30',
    aemporterOrderEyebrow: 'COMMANDE', aemporterOrderText: 'Par téléphone, la veille de préférence', aemporterCta: 'APPELER POUR COMMANDER',
    gitesEyebrow: 'SÉJOURNER AU RELAIS', gitesTitle: 'Le Gîte',
    gitesTagline: 'Une maison restaurée avec soin, à deux pas du restaurant. Quatre chambres indépendantes, à réserver séparément, chacune avec son caractère.',
    gitesEvCharger: 'Borne de recharge pour véhicules électriques sur place',
    gitesDetail1: 'Détail 1', gitesDetail2: 'Détail 2', gitesDetail3: 'Détail 3',
    gitesCtaTitle: 'Envie de séjourner au relais ?', gitesCtaText: 'Chaque chambre se réserve indépendamment, par téléphone ou par écrit. Nous composerons votre séjour avec vous.',
    spaEyebrow: 'SILENCE · CALME · EAU', spaTitle: 'Le Spa', spaTagline: 'Un lieu clos, feutré, réservé aux hôtes du relais.',
    practiceEyebrow: 'EN PRATIQUE', practiceTitle: 'Accès au spa',
    practice1Title: 'Ouvert tous les jours', practice1Text: '10h00 – 20h00, sur créneaux privatisés',
    practice2Title: 'Réservé aux hôtes', practice2Text: 'Inclus pour les séjours en gîte, sur demande au restaurant',
    practice3Title: 'Linge fourni', practice3Text: 'Peignoirs, serviettes et chaussons à disposition',
    ctaBookSlot: 'RÉSERVER UN CRÉNEAU',
    contactEyebrow: 'CONTACT', contactTitle1: 'Écrivez-nous,', contactTitle2: 'ou passez nous voir.',
    addressLabel: 'ADRESSE', phoneLabel: 'TÉLÉPHONE', emailLabel: 'EMAIL',
    contactHours: 'Accueil du lundi au dimanche, 9h – 19h.', contactHours2: 'Restaurant, gîte et spa : toute demande se fait par téléphone ou email — nous répondons sous 24h.',
    formNameLabel: 'NOM', formFirstNameLabel: 'PRÉNOM', formEmailLabel: 'EMAIL', formMessageLabel: 'MESSAGE',
    formNamePh: 'Votre nom', formFirstNamePh: 'Votre prénom', formEmailPh: 'vous@exemple.com', formMessagePh: 'Votre message…',
    formSendBtn: 'ENVOYER LE MESSAGE', formNote: "En cliquant sur envoyer, votre messagerie s'ouvrira avec ce message pré-rempli.",
    recruitEyebrow: 'REJOIGNEZ-NOUS', recruitTitle: 'Recrutement', recruitTagline: 'Le Méandre grandit avec les personnes qui y travaillent.',
    recruitParagraph: "Nous recrutons régulièrement en cuisine, en salle et pour l'entretien du relais et du gîte. Aucun poste ouvert ne vous correspond aujourd'hui ? Envoyez-nous une candidature spontanée : nous gardons chaque CV et reprenons contact dès qu'un poste s'ouvre.",
    recruitCta: 'ENVOYER MA CANDIDATURE', recruitEmailNote: 'CV et lettre de motivation à :',
    sceneEyebrow: 'SCÈNE & ART', sceneTitle: 'Le Méandre ouvre sa scène', sceneTagline: 'Vous êtes artiste ?',
    sceneParagraph: 'Vous êtes musicien, peintre, photographe, humoriste ou artiste du spectacle vivant ? Vous souhaitez exposer, vous produire ou imaginer un projet avec nous ? Nous sommes toujours à la recherche de nouveaux univers et de nouvelles sensibilités à faire découvrir à nos hôtes.',
    sceneFormIntro: 'Proposez votre univers', sceneCta: 'JE PROPOSE MON PROJET',
    sceneDisciplineLabel: 'DISCIPLINE', sceneDisciplinePh: 'Musique, peinture, photographie, spectacle vivant…',
    sceneProjectLabel: 'VOTRE PROJET', sceneProjectPh: 'Décrivez votre univers, votre projet, vos disponibilités…',
    sceneFormNote: "En cliquant sur envoyer, votre messagerie s'ouvrira avec ce message pré-rempli.",
    navAgenda: 'AGENDA',
    agendaEyebrow: 'CONCERTS · MARCHÉS · SOIRÉES', agendaTitle: "L'Agenda",
    agendaTagline: 'Les prochains rendez-vous organisés au Méandre : soirées à thème, concerts, marchés de producteurs et moments à partager.',
    agendaEmptyTitle: 'Aucune date pour le moment', agendaEmptyText: "Notre agenda est en préparation — revenez bientôt, ou contactez-nous pour être informé des prochains événements.",
    sinceWord: 'DEPUIS',
    phHero: 'Photo du relais — vue extérieure, grand format', phAccRest: 'Plat signature', phAccGites: "Intérieur du gîte", phAccSpa: 'Spa',
    phRestHero: 'Salle du restaurant ou plat — bandeau large', phSpaHero: 'Spa — grand format immersif', phContact: "Photo — allée, portail ou plan d'accès",
    phAEmporter: "Affiche de l'offre à emporter du moment — format portrait", aemporterCaption: '(photo non contractuelle)'
  },
  en: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'TAKEAWAY', navGites: 'THE COTTAGE', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'CAREERS', footerScene: 'STAGE & ART',
    heroTagline: 'Restaurant, cottage and spa in a former coaching inn steeped in history, at the heart of the Course Valley.',
    cardRestTitle: 'The Restaurant', cardRestDesc: 'Refined, seasonal dining between land and sea.',
    cardGitesTitle: 'The Cottage', cardGitesDesc: 'Four independent rooms, bookable separately, within the same house.',
    cardSpaTitle: 'The Spa', cardSpaDesc: 'A spa, in absolute quiet.',
    discover: 'DISCOVER →',
    artEyebrow: 'ESTRÉE · COURSE VALLEY', artTitle1: 'Welcome', artTitle2: 'to Le Méandre',
    artPara1: "At the heart of the Course Valley, in Estrée, Le Méandre welcomes you to a place steeped in history, where the art of hospitality has been passed down for several years.",
    artPara2: "A former coaching inn and address dedicated to welcoming travellers, the house has lived several lives before writing, today, a new chapter under the name Le Méandre.",
    artPara3: "Our establishment brings together a restaurant, a cottage and a spa, in a warm and refined spirit.",
    artCuisineTitle: "A refined cuisine, between land and sea, through the seasons",
    artPara4: "At the restaurant, we champion a gourmet, elegant and seasonal cuisine, inspired by our terroir and the nearby Opal Coast. Seafood holds a place of honour here, alongside local produce and beautiful culinary inspirations.",
    artPara5: "Our ambition: to offer you an exceptional table, in a setting where you take the time to share, discover and enjoy.",
    artPara6: "Le Méandre is a new story, unfolding along the Course.",
    artTagline: "Restaurant · Cottage · Spa",
    ctaContact: 'CONTACT US',
    eventEyebrow: 'SEMINARS · WEDDINGS · RECEPTIONS', eventTitle: 'Events',
    eventTagline: 'The inn also lends itself to your milestone moments: weddings, corporate seminars, private receptions or family gatherings.',
    eventParagraph: "Reception room, terrace, garden and private lounge, our restaurant's kitchen and cottage for guest accommodation: we tailor every event, from a cocktail in the garden to dinner in our private lounge.",
    eventCta: 'REQUEST A QUOTE',
    restTitle: 'The Restaurant',
    menuEyebrow: 'THE MENU', menuTitle: 'The Menu',
    menuTerroirTitle: 'Terroir Menu', menuTerroirSub: 'Starter · Main · Dessert',
    menuEstreeTitle: 'Signature Menu', menuEstreeSub: 'Six-course tasting menu, wine pairings',
    galleryEyebrow: 'GALLERY', galleryTitle: 'The table, the room, the atmosphere',
    hoursEyebrow: 'HOURS', hoursText: 'Wednesday to Sunday', hoursLunch: 'Lunch · 12:00 – 1:30 PM', hoursDinner: 'Dinner · 7:30 – 9:30 PM', hoursClosed: 'Closed Monday and Tuesday',
    cuisineEyebrow: 'THE KITCHEN', cuisineText: 'Refined · Land and Sea', cuisineText2: 'Seafood and local producers', cuisineText3: 'Menu refreshed every season',
    resaEyebrow: 'RESERVATIONS', resaText: 'By phone only',
    accessEyebrow: 'GETTING HERE', accessMapCta: 'View directions on Google Maps →',
    aemporterEyebrow: 'TAKEAWAY', aemporterTitle: 'Takeaway', aemporterTagline: "The restaurant's cooking, to enjoy at home.",
    aemporterParagraph: 'Slow-cooked dishes, starters and desserts prepared by our kitchen, ready for pickup. The menu changes with the season and the market — call us to hear the dishes of the day.',
    aemporterHoursText: 'Pickup Wednesday to Sunday', aemporterHoursLunch: '12:00 – 1:30 PM', aemporterHoursDinner: '7:00 – 8:30 PM',
    aemporterOrderEyebrow: 'ORDERING', aemporterOrderText: 'By phone, ideally the day before', aemporterCta: 'CALL TO ORDER',
    gitesEyebrow: 'STAY AT THE INN', gitesTitle: 'The Cottage',
    gitesTagline: "A carefully restored house, just steps from the restaurant. Four independent rooms, each bookable separately, each with its own character.",
    gitesEvCharger: 'On-site electric vehicle charging station',
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Fancy a stay at the inn?', gitesCtaText: "Each room is booked independently, by phone or in writing. We'll put together your stay with you.",
    spaEyebrow: 'SILENCE · CALM · WATER', spaTitle: 'The Spa', spaTagline: 'A hushed, enclosed retreat reserved for the inn\'s guests.',
    practiceEyebrow: 'GOOD TO KNOW', practiceTitle: 'Spa access',
    practice1Title: 'Open every day', practice1Text: '10:00 AM – 8:00 PM, in private slots',
    practice2Title: 'Reserved for guests', practice2Text: 'Included with cottage stays, on request at the restaurant',
    practice3Title: 'Linens provided', practice3Text: 'Robes, towels and slippers provided',
    ctaBookSlot: 'BOOK A SLOT',
    contactEyebrow: 'CONTACT', contactTitle1: 'Write to us,', contactTitle2: 'or come see us.',
    addressLabel: 'ADDRESS', phoneLabel: 'PHONE', emailLabel: 'EMAIL',
    contactHours: 'Open Monday to Sunday, 9 AM – 7 PM.', contactHours2: 'Restaurant, cottage and spa: all requests by phone or email — we reply within 24h.',
    formNameLabel: 'LAST NAME', formFirstNameLabel: 'FIRST NAME', formEmailLabel: 'EMAIL', formMessageLabel: 'MESSAGE',
    formNamePh: 'Your last name', formFirstNamePh: 'Your first name', formEmailPh: 'you@example.com', formMessagePh: 'Your message…',
    formSendBtn: 'SEND MESSAGE', formNote: 'Clicking send will open your mail app with this message pre-filled.',
    recruitEyebrow: 'JOIN US', recruitTitle: 'Careers', recruitTagline: 'Le Méandre grows with the people who work here.',
    recruitParagraph: 'We regularly hire in the kitchen, the dining room, and for the upkeep of the inn and cottage. Nothing open that matches you today? Send us a spontaneous application: we keep every CV on file and get back in touch as soon as a position opens.',
    recruitCta: 'SEND MY APPLICATION', recruitEmailNote: 'CV and cover letter to:',
    sceneEyebrow: 'STAGE & ART', sceneTitle: 'Le Méandre opens its stage', sceneTagline: 'Are you an artist?',
    sceneParagraph: 'Are you a musician, painter, photographer, comedian or performing artist? Would you like to exhibit, perform, or imagine a project with us? We are always looking for new worlds and new sensibilities to introduce to our guests.',
    sceneFormIntro: 'Propose your world', sceneCta: 'PROPOSE MY PROJECT',
    sceneDisciplineLabel: 'DISCIPLINE', sceneDisciplinePh: 'Music, painting, photography, live performance…',
    sceneProjectLabel: 'YOUR PROJECT', sceneProjectPh: 'Describe your world, your project, your availability…',
    sceneFormNote: 'Clicking send will open your mail app with this message pre-filled.',
    navAgenda: 'AGENDA',
    agendaEyebrow: 'CONCERTS · MARKETS · EVENINGS', agendaTitle: 'The Agenda',
    agendaTagline: "Upcoming get-togethers at Le Méandre: themed evenings, concerts, producers' markets and moments to share.",
    agendaEmptyTitle: 'No dates just yet', agendaEmptyText: "Our agenda is being put together — check back soon, or contact us to hear about upcoming events.",
    sinceWord: 'SINCE',
    phHero: 'Inn photo — exterior view, large format', phAccRest: 'Signature dish', phAccGites: 'Cottage interior', phAccSpa: 'Spa',
    phRestHero: 'Dining room or dish — wide banner', phSpaHero: 'Spa — large immersive format', phContact: 'Photo — driveway, gate or access map',
    phAEmporter: "Current takeaway offer poster — portrait format", aemporterCaption: '(non-contractual photo)'
  },
  de: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'ZUM MITNEHMEN', navGites: 'DAS GÎTE', navSpa: 'SPA', navContact: 'KONTAKT',
    footerRecrutement: 'KARRIERE', footerScene: 'BÜHNE & KUNST',
    heroTagline: 'Restaurant, Gîte und Spa in einer alten, geschichtsträchtigen Poststation im Herzen des Course-Tals.',
    cardRestTitle: 'Das Restaurant', cardRestDesc: 'Eine raffinierte, saisonale Küche zwischen Land und Meer.',
    cardGitesTitle: 'Das Gîte', cardGitesDesc: 'Vier unabhängige Zimmer, einzeln buchbar, im selben Haus.',
    cardSpaTitle: 'Der Spa', cardSpaDesc: 'Ein Spa, in vollkommener Ruhe.',
    discover: 'ENTDECKEN →',
    artEyebrow: 'ESTRÉE · COURSE-TAL', artTitle1: 'Willkommen', artTitle2: 'im Méandre',
    artPara1: 'Im Herzen des Course-Tals, in Estrée, empfängt Sie Le Méandre an einem geschichtsträchtigen Ort, an dem die Kunst der Gastfreundschaft seit mehreren Jahren weitergegeben wird.',
    artPara2: 'Als ehemalige Poststation und Adresse für empfangene Reisende hat das Haus mehrere Leben durchlebt, bevor es heute unter dem Namen Le Méandre ein neues Kapitel aufschlägt.',
    artPara3: 'Unser Haus vereint Restaurant, Gîte und Spa in einem herzlichen und raffinierten Geist.',
    artCuisineTitle: 'Eine raffinierte Küche, zwischen Land und Meer, im Wandel der Jahreszeiten',
    artPara4: "Im Restaurant setzen wir auf eine raffinierte, elegante und saisonale Küche, inspiriert von unserem Terroir und der Nähe zur Côte d'Opale. Meeresfrüchte nehmen hier einen besonderen Platz ein, ergänzt durch lokale Produkte und schöne kulinarische Inspirationen.",
    artPara5: 'Unser Anspruch: Ihnen einen außergewöhnlichen Tisch zu bieten, in einem Rahmen, in dem man sich Zeit nimmt zu teilen, zu entdecken und zu genießen.',
    artPara6: 'Le Méandre — das ist eine neue Geschichte, die sich entlang der Course schreibt.',
    artTagline: 'Restaurant · Gîte · Spa',
    ctaContact: 'KONTAKTIEREN SIE UNS',
    eventEyebrow: 'SEMINARE · HOCHZEITEN · EMPFÄNGE', eventTitle: 'Veranstaltungen',
    eventTagline: 'Der Gasthof eignet sich auch für Ihre besonderen Momente: Hochzeiten, Firmenseminare, private Empfänge oder Familienfeiern.',
    eventParagraph: 'Empfangssaal, Terrasse, Garten und privater Salon, die Küche unseres Restaurants und das Gîte für die Unterbringung der Gäste: Wir gestalten jede Veranstaltung individuell, vom Cocktailempfang im Garten bis zum Dinner in unserem privaten Salon.',
    eventCta: 'ANGEBOT ANFORDERN',
    restTitle: 'Das Restaurant',
    menuEyebrow: 'DIE KARTE', menuTitle: 'Die Speisekarte',
    menuTerroirTitle: 'Menü Terroir', menuTerroirSub: 'Vorspeise · Hauptgang · Dessert',
    menuEstreeTitle: 'Signature-Menü', menuEstreeSub: 'Sechsgängiges Degustationsmenü mit Weinbegleitung',
    galleryEyebrow: 'BILDER', galleryTitle: 'Die Tafel, der Saal, die Atmosphäre',
    hoursEyebrow: 'ÖFFNUNGSZEITEN', hoursText: 'Mittwoch bis Sonntag', hoursLunch: 'Mittagessen · 12:00 – 13:30 Uhr', hoursDinner: 'Abendessen · 19:30 – 21:30 Uhr', hoursClosed: 'Montag und Dienstag geschlossen',
    cuisineEyebrow: 'DIE KÜCHE', cuisineText: 'Raffiniert · Land und Meer', cuisineText2: 'Meeresfrüchte und lokale Erzeuger', cuisineText3: 'Karte wechselt jede Saison',
    resaEyebrow: 'RESERVIERUNG', resaText: 'Nur telefonisch',
    accessEyebrow: 'ANFAHRT', accessMapCta: 'Route auf Google Maps anzeigen →',
    aemporterEyebrow: 'ZUM MITNEHMEN', aemporterTitle: 'Gerichte zum Mitnehmen', aemporterTagline: 'Die Küche des Restaurants, zu Hause genießen.',
    aemporterParagraph: 'Geschmorte Gerichte, Vorspeisen und Desserts, zubereitet von unserer Küche und zur Abholung bereit. Die Karte ändert sich je nach Saison und Angebot — rufen Sie uns an, um die Tagesgerichte zu erfahren.',
    aemporterHoursText: 'Abholung Mittwoch bis Sonntag', aemporterHoursLunch: '12:00 – 13:30 Uhr', aemporterHoursDinner: '19:00 – 20:30 Uhr',
    aemporterOrderEyebrow: 'BESTELLUNG', aemporterOrderText: 'Telefonisch, idealerweise am Vortag', aemporterCta: 'TELEFONISCH BESTELLEN',
    gitesEyebrow: 'AUFENTHALT IM GASTHOF', gitesTitle: 'Das Gîte',
    gitesTagline: 'Ein sorgfältig restauriertes Haus, nur wenige Schritte vom Restaurant entfernt. Vier unabhängige Zimmer, jedes einzeln buchbar und mit eigenem Charakter.',
    gitesEvCharger: 'Ladestation für Elektrofahrzeuge vor Ort',
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Lust auf einen Aufenthalt im Gasthof?', gitesCtaText: 'Jedes Zimmer wird unabhängig gebucht, telefonisch oder schriftlich. Wir stellen Ihren Aufenthalt gemeinsam mit Ihnen zusammen.',
    spaEyebrow: 'STILLE · RUHE · WASSER', spaTitle: 'Der Spa', spaTagline: 'Ein abgeschiedener, gedämpfter Ort, den Gästen des Gasthofs vorbehalten.',
    practiceEyebrow: 'GUT ZU WISSEN', practiceTitle: 'Zugang zum Spa',
    practice1Title: 'Täglich geöffnet', practice1Text: '10:00 – 20:00 Uhr, in privatisierten Zeitfenstern',
    practice2Title: 'Nur für Gäste', practice2Text: 'Inklusive bei Aufenthalten im Gîte, auf Anfrage im Restaurant',
    practice3Title: 'Wäsche gestellt', practice3Text: 'Bademäntel, Handtücher und Hausschuhe stehen zur Verfügung',
    ctaBookSlot: 'ZEITFENSTER BUCHEN',
    contactEyebrow: 'KONTAKT', contactTitle1: 'Schreiben Sie uns,', contactTitle2: 'oder besuchen Sie uns.',
    addressLabel: 'ADRESSE', phoneLabel: 'TELEFON', emailLabel: 'E-MAIL',
    contactHours: 'Empfang von Montag bis Sonntag, 9 – 19 Uhr.', contactHours2: 'Restaurant, Gîte und Spa: Alle Anfragen telefonisch oder per E-Mail — wir antworten innerhalb von 24 Stunden.',
    formNameLabel: 'NAME', formFirstNameLabel: 'VORNAME', formEmailLabel: 'E-MAIL', formMessageLabel: 'NACHRICHT',
    formNamePh: 'Ihr Name', formFirstNamePh: 'Ihr Vorname', formEmailPh: 'sie@beispiel.com', formMessagePh: 'Ihre Nachricht…',
    formSendBtn: 'NACHRICHT SENDEN', formNote: 'Beim Klicken auf Senden öffnet sich Ihr E-Mail-Programm mit dieser vorausgefüllten Nachricht.',
    recruitEyebrow: 'WERDEN SIE TEIL DES TEAMS', recruitTitle: 'Karriere', recruitTagline: 'Le Méandre wächst mit den Menschen, die hier arbeiten.',
    recruitParagraph: 'Wir stellen regelmäßig in der Küche, im Service sowie für die Pflege des Gasthofs und des Gîtes ein. Ist heute nichts Passendes dabei? Schicken Sie uns eine Initiativbewerbung: Wir bewahren jeden Lebenslauf auf und melden uns, sobald eine Stelle frei wird.',
    recruitCta: 'BEWERBUNG SENDEN', recruitEmailNote: 'Lebenslauf und Anschreiben an:',
    sceneEyebrow: 'BÜHNE & KUNST', sceneTitle: 'Le Méandre öffnet seine Bühne', sceneTagline: 'Sind Sie Künstler?',
    sceneParagraph: 'Sind Sie Musiker, Maler, Fotograf, Komiker oder darstellender Künstler? Möchten Sie ausstellen, auftreten oder ein Projekt mit uns entwickeln? Wir sind stets auf der Suche nach neuen Welten und neuen Sensibilitäten, die wir unseren Gästen vorstellen können.',
    sceneFormIntro: 'Stellen Sie Ihre Welt vor', sceneCta: 'MEIN PROJEKT VORSCHLAGEN',
    sceneDisciplineLabel: 'DISZIPLIN', sceneDisciplinePh: 'Musik, Malerei, Fotografie, darstellende Kunst…',
    sceneProjectLabel: 'IHR PROJEKT', sceneProjectPh: 'Beschreiben Sie Ihre Welt, Ihr Projekt, Ihre Verfügbarkeit…',
    sceneFormNote: 'Beim Klicken auf Senden öffnet sich Ihr E-Mail-Programm mit dieser vorausgefüllten Nachricht.',
    navAgenda: 'AGENDA',
    agendaEyebrow: 'KONZERTE · MÄRKTE · ABENDE', agendaTitle: 'Die Agenda',
    agendaTagline: 'Die nächsten Termine im Méandre: Themenabende, Konzerte, Erzeugermärkte und Momente zum Teilen.',
    agendaEmptyTitle: 'Noch keine Termine', agendaEmptyText: 'Unser Terminkalender wird gerade zusammengestellt — schauen Sie bald wieder vorbei oder kontaktieren Sie uns, um über kommende Veranstaltungen informiert zu werden.',
    sinceWord: 'SEIT',
    phHero: 'Foto des Gasthofs — Außenansicht, Großformat', phAccRest: 'Signature-Gericht', phAccGites: 'Inneres des Gîte', phAccSpa: 'Spa',
    phRestHero: 'Speisesaal oder Gericht — breites Banner', phSpaHero: 'Spa — großformatig, immersiv', phContact: 'Foto — Zufahrt, Tor oder Lageplan',
    phAEmporter: 'Plakat des aktuellen Angebots zum Mitnehmen — Hochformat', aemporterCaption: '(unverbindliches Foto)'
  },
  es: {
    navRestaurant: 'RESTAURANTE', navAEmporter: 'PARA LLEVAR', navGites: 'LA CASA RURAL', navSpa: 'SPA', navContact: 'CONTACTO',
    footerRecrutement: 'EMPLEO', footerScene: 'ESCENA Y ARTE',
    heroTagline: 'Restaurante, casa rural y spa en una antigua posada cargada de historia, en el corazón del Valle del Course.',
    cardRestTitle: 'El Restaurante', cardRestDesc: 'Una cocina refinada de temporada, entre tierra y mar.',
    cardGitesTitle: 'La Casa Rural', cardGitesDesc: 'Cuatro habitaciones independientes, reservables por separado, en la misma casa.',
    cardSpaTitle: 'El Spa', cardSpaDesc: 'Un spa, en una calma absoluta.',
    discover: 'DESCUBRIR →',
    artEyebrow: 'ESTRÉE · VALLE DEL COURSE', artTitle1: 'Bienvenidos', artTitle2: 'al Méandre',
    artPara1: 'En el corazón del Valle del Course, en Estrée, Le Méandre le recibe en un lugar cargado de historia, donde el arte de recibir se transmite desde hace varios años.',
    artPara2: 'Antigua posada y dirección dedicada a acoger a los viajeros, la casa ha vivido varias vidas antes de escribir hoy un nuevo capítulo bajo el nombre de Le Méandre.',
    artPara3: 'Nuestro establecimiento combina restaurante, casa rural y spa, en un espíritu cálido y refinado.',
    artCuisineTitle: 'Una cocina refinada, entre tierra y mar, al hilo de las estaciones',
    artPara4: 'En el restaurante, defendemos una cocina golosa, elegante y de temporada, inspirada en nuestro terruño y la cercanía de la Costa de Ópalo. Los productos del mar ocupan aquí un lugar privilegiado, acompañados de productos locales y bellas inspiraciones culinarias.',
    artPara5: 'Nuestra ambición: ofrecerle una mesa de excepción, en un entorno donde uno se toma el tiempo de compartir, descubrir y disfrutar.',
    artPara6: 'Le Méandre es una nueva historia que se escribe a orillas del Course.',
    artTagline: 'Restaurante · Casa Rural · Spa',
    ctaContact: 'CONTÁCTENOS',
    eventEyebrow: 'SEMINARIOS · BODAS · RECEPCIONES', eventTitle: 'Eventos',
    eventTagline: 'La posada también se presta a sus grandes momentos: bodas, seminarios de empresa, recepciones privadas o comidas familiares.',
    eventParagraph: 'Sala de recepciones, terraza, jardín y salón privado, la cocina de nuestro restaurante y la casa rural para alojar a los invitados: diseñamos cada evento a medida, desde un cóctel en el jardín hasta la cena en nuestro salón privado.',
    eventCta: 'SOLICITAR PRESUPUESTO',
    restTitle: 'El Restaurante',
    menuEyebrow: 'LA CARTA', menuTitle: 'El Menú',
    menuTerroirTitle: 'Menú Terruño', menuTerroirSub: 'Entrante · Plato · Postre',
    menuEstreeTitle: 'Menú Signature', menuEstreeSub: 'Degustación en seis tiempos, maridaje de vinos',
    galleryEyebrow: 'GALERÍA', galleryTitle: 'La mesa, la sala, el ambiente',
    hoursEyebrow: 'HORARIOS', hoursText: 'De miércoles a domingo', hoursLunch: 'Comida · 12:00 – 13:30 h', hoursDinner: 'Cena · 19:30 – 21:30 h', hoursClosed: 'Cerrado lunes y martes',
    cuisineEyebrow: 'LA COCINA', cuisineText: 'Refinada · Tierra y Mar', cuisineText2: 'Productos del mar y productores locales', cuisineText3: 'Carta renovada cada temporada',
    resaEyebrow: 'RESERVAS', resaText: 'Solo por teléfono',
    accessEyebrow: 'CÓMO LLEGAR', accessMapCta: 'Ver ruta en Google Maps →',
    aemporterEyebrow: 'PARA LLEVAR', aemporterTitle: 'Para Llevar', aemporterTagline: 'La cocina del restaurante, para disfrutar en casa.',
    aemporterParagraph: 'Platos cocinados a fuego lento, entrantes y postres preparados por nuestra cocina, listos para recoger. La carta cambia según la temporada y el mercado — llámenos para conocer los platos del día.',
    aemporterHoursText: 'Recogida de miércoles a domingo', aemporterHoursLunch: '12:00 – 13:30 h', aemporterHoursDinner: '19:00 – 20:30 h',
    aemporterOrderEyebrow: 'PEDIDOS', aemporterOrderText: 'Por teléfono, preferiblemente el día anterior', aemporterCta: 'LLAMAR PARA PEDIR',
    gitesEyebrow: 'ALOJARSE EN LA POSADA', gitesTitle: 'La Casa Rural',
    gitesTagline: 'Una casa restaurada con esmero, a pocos pasos del restaurante. Cuatro habitaciones independientes, cada una reservable por separado y con su propio carácter.',
    gitesEvCharger: 'Punto de recarga para vehículos eléctricos en el lugar',
    gitesDetail1: 'Detalle 1', gitesDetail2: 'Detalle 2', gitesDetail3: 'Detalle 3',
    gitesCtaTitle: '¿Le apetece alojarse en la posada?', gitesCtaText: 'Cada habitación se reserva de forma independiente, por teléfono o por escrito. Diseñaremos su estancia junto a usted.',
    spaEyebrow: 'SILENCIO · CALMA · AGUA', spaTitle: 'El Spa', spaTagline: 'Un espacio cerrado y aterciopelado, reservado a los huéspedes de la posada.',
    practiceEyebrow: 'INFORMACIÓN PRÁCTICA', practiceTitle: 'Acceso al spa',
    practice1Title: 'Abierto todos los días', practice1Text: '10:00 – 20:00 h, en franjas privatizadas',
    practice2Title: 'Reservado a los huéspedes', practice2Text: 'Incluido en las estancias en la casa rural, bajo petición en el restaurante',
    practice3Title: 'Ropa de baño incluida', practice3Text: 'Albornoces, toallas y zapatillas a su disposición',
    ctaBookSlot: 'RESERVAR UNA FRANJA',
    contactEyebrow: 'CONTACTO', contactTitle1: 'Escríbanos,', contactTitle2: 'o venga a vernos.',
    addressLabel: 'DIRECCIÓN', phoneLabel: 'TELÉFONO', emailLabel: 'CORREO ELECTRÓNICO',
    contactHours: 'Recepción de lunes a domingo, 9 – 19 h.', contactHours2: 'Restaurante, casa rural y spa: toda solicitud por teléfono o correo electrónico — respondemos en 24 h.',
    formNameLabel: 'APELLIDO', formFirstNameLabel: 'NOMBRE', formEmailLabel: 'CORREO ELECTRÓNICO', formMessageLabel: 'MENSAJE',
    formNamePh: 'Su apellido', formFirstNamePh: 'Su nombre', formEmailPh: 'usted@ejemplo.com', formMessagePh: 'Su mensaje…',
    formSendBtn: 'ENVIAR MENSAJE', formNote: 'Al hacer clic en enviar, se abrirá su aplicación de correo con este mensaje ya redactado.',
    recruitEyebrow: 'ÚNASE A NOSOTROS', recruitTitle: 'Empleo', recruitTagline: 'Le Méandre crece con las personas que trabajan aquí.',
    recruitParagraph: 'Contratamos regularmente en cocina, en sala y para el mantenimiento de la posada y la casa rural. ¿Ningún puesto abierto le corresponde hoy? Envíenos una candidatura espontánea: guardamos cada currículum y le contactamos en cuanto se abra un puesto.',
    recruitCta: 'ENVIAR MI CANDIDATURA', recruitEmailNote: 'CV y carta de motivación a:',
    sceneEyebrow: 'ESCENA Y ARTE', sceneTitle: 'Le Méandre abre su escenario', sceneTagline: '¿Es usted artista?',
    sceneParagraph: '¿Es usted músico, pintor, fotógrafo, humorista o artista de las artes escénicas? ¿Desea exponer, actuar o imaginar un proyecto con nosotros? Siempre estamos buscando nuevos universos y nuevas sensibilidades que dar a conocer a nuestros huéspedes.',
    sceneFormIntro: 'Proponga su universo', sceneCta: 'PROPONER MI PROYECTO',
    sceneDisciplineLabel: 'DISCIPLINA', sceneDisciplinePh: 'Música, pintura, fotografía, artes escénicas…',
    sceneProjectLabel: 'SU PROYECTO', sceneProjectPh: 'Describa su universo, su proyecto, su disponibilidad…',
    sceneFormNote: 'Al hacer clic en enviar, se abrirá su aplicación de correo con este mensaje ya redactado.',
    navAgenda: 'AGENDA',
    agendaEyebrow: 'CONCIERTOS · MERCADOS · VELADAS', agendaTitle: 'La Agenda',
    agendaTagline: 'Las próximas citas en Le Méandre: veladas temáticas, conciertos, mercados de productores y momentos para compartir.',
    agendaEmptyTitle: 'Sin fechas por el momento', agendaEmptyText: 'Nuestra agenda está en preparación — vuelva pronto, o contáctenos para conocer los próximos eventos.',
    sinceWord: 'DESDE',
    phHero: 'Foto de la posada — vista exterior, gran formato', phAccRest: 'Plato signature', phAccGites: 'Interior de la casa rural', phAccSpa: 'Spa',
    phRestHero: 'Sala del restaurante o plato — banner ancho', phSpaHero: 'Spa — gran formato inmersivo', phContact: 'Foto — camino de acceso, portón o plano de acceso',
    phAEmporter: 'Cartel de la oferta actual para llevar — formato vertical', aemporterCaption: '(foto no contractual)'
  },
  nl: {
    navRestaurant: 'RESTAURANT', navAEmporter: 'AFHALEN', navGites: 'DE GÎTE', navSpa: 'SPA', navContact: 'CONTACT',
    footerRecrutement: 'VACATURES', footerScene: 'PODIUM & KUNST',
    heroTagline: 'Restaurant, gîte en spa in een voormalige pleisterplaats vol geschiedenis, in het hart van de Course-vallei.',
    cardRestTitle: 'Het Restaurant', cardRestDesc: 'Een verfijnde, seizoensgebonden keuken tussen land en zee.',
    cardGitesTitle: 'De Gîte', cardGitesDesc: 'Vier onafhankelijke kamers, apart te boeken, in hetzelfde huis.',
    cardSpaTitle: 'De Spa', cardSpaDesc: 'Een spa, in volstrekte rust.',
    discover: 'ONTDEKKEN →',
    artEyebrow: 'ESTRÉE · COURSE-VALLEI', artTitle1: 'Welkom', artTitle2: 'bij Le Méandre',
    artPara1: 'In het hart van de Course-vallei, in Estrée, verwelkomt Le Méandre u op een plek vol geschiedenis, waar de kunst van gastvrijheid al enkele jaren wordt doorgegeven.',
    artPara2: 'Als voormalige pleisterplaats en adres gewijd aan het onthaal van reizigers, heeft het huis meerdere levens gekend voordat het vandaag een nieuw hoofdstuk schrijft onder de naam Le Méandre.',
    artPara3: 'Ons huis verenigt restaurant, gîte en spa, in een warme en verfijnde sfeer.',
    artCuisineTitle: 'Een verfijnde keuken, tussen land en zee, met de seizoenen mee',
    artPara4: 'In het restaurant staan wij voor een smakelijke, elegante en seizoensgebonden keuken, geïnspireerd door ons terroir en de nabijheid van de Opaalkust. Zeeproducten nemen hier een bevoorrechte plaats in, samen met lokale producten en mooie culinaire inspiraties.',
    artPara5: 'Onze ambitie: u een uitzonderlijke tafel bieden, in een kader waar men de tijd neemt om te delen, te ontdekken en te genieten.',
    artPara6: 'Le Méandre, dat is een nieuw verhaal dat zich schrijft langs de Course.',
    artTagline: 'Restaurant · Gîte · Spa',
    ctaContact: 'NEEM CONTACT OP',
    eventEyebrow: 'SEMINARS · BRUILOFTEN · RECEPTIES', eventTitle: 'Evenementen',
    eventTagline: 'De herberg leent zich ook voor uw bijzondere momenten: bruiloften, bedrijfsseminars, privérecepties of familiediners.',
    eventParagraph: 'Ontvangstzaal, terras, tuin en privésalon, de keuken van ons restaurant en de gîte voor de overnachting van gasten: wij stellen elk evenement op maat samen, van een cocktail in de tuin tot een diner in onze privésalon.',
    eventCta: 'OFFERTE AANVRAGEN',
    restTitle: 'Het Restaurant',
    menuEyebrow: 'DE KAART', menuTitle: 'Het Menu',
    menuTerroirTitle: 'Menu Terroir', menuTerroirSub: 'Voorgerecht · Hoofdgerecht · Dessert',
    menuEstreeTitle: 'Signature Menu', menuEstreeSub: 'Zesgangen proeverij, met wijnbegeleiding',
    galleryEyebrow: 'IN BEELD', galleryTitle: 'De tafel, de zaal, de sfeer',
    hoursEyebrow: 'OPENINGSTIJDEN', hoursText: 'Woensdag tot en met zondag', hoursLunch: 'Lunch · 12:00 – 13:30 uur', hoursDinner: 'Diner · 19:30 – 21:30 uur', hoursClosed: 'Gesloten op maandag en dinsdag',
    cuisineEyebrow: 'DE KEUKEN', cuisineText: 'Verfijnd · Land en Zee', cuisineText2: 'Zeeproducten en lokale producenten', cuisineText3: 'Kaart elk seizoen vernieuwd',
    resaEyebrow: 'RESERVERING', resaText: 'Uitsluitend telefonisch',
    accessEyebrow: 'BEREIKBAARHEID', accessMapCta: 'Bekijk route op Google Maps →',
    aemporterEyebrow: 'AFHALEN', aemporterTitle: 'Afhaalgerechten', aemporterTagline: 'De keuken van het restaurant, thuis te genieten.',
    aemporterParagraph: 'Stoofgerechten, voorgerechten en desserts bereid door onze keuken, klaar om af te halen. De kaart verandert met het seizoen en het aanbod — bel ons voor de gerechten van de dag.',
    aemporterHoursText: 'Afhalen van woensdag tot zondag', aemporterHoursLunch: '12:00 – 13:30 uur', aemporterHoursDinner: '19:00 – 20:30 uur',
    aemporterOrderEyebrow: 'BESTELLEN', aemporterOrderText: 'Telefonisch, bij voorkeur de dag ervoor', aemporterCta: 'BEL OM TE BESTELLEN',
    gitesEyebrow: 'VERBLIJVEN IN DE HERBERG', gitesTitle: 'De Gîte',
    gitesTagline: 'Een zorgvuldig gerestaureerd huis, op enkele stappen van het restaurant. Vier onafhankelijke kamers, elk apart te boeken en met hun eigen karakter.',
    gitesEvCharger: 'Oplaadpunt voor elektrische voertuigen ter plaatse',
    gitesDetail1: 'Detail 1', gitesDetail2: 'Detail 2', gitesDetail3: 'Detail 3',
    gitesCtaTitle: 'Zin om in de herberg te verblijven?', gitesCtaText: 'Elke kamer wordt onafhankelijk geboekt, telefonisch of schriftelijk. Wij stellen uw verblijf samen met u samen.',
    spaEyebrow: 'STILTE · RUST · WATER', spaTitle: 'De Spa', spaTagline: 'Een besloten, gedempte plek, voorbehouden aan de gasten van de herberg.',
    practiceEyebrow: 'PRAKTISCHE INFORMATIE', practiceTitle: 'Toegang tot de spa',
    practice1Title: 'Elke dag geopend', practice1Text: '10:00 – 20:00 uur, in geprivatiseerde tijdsloten',
    practice2Title: 'Voorbehouden aan gasten', practice2Text: 'Inbegrepen bij een verblijf in de gîte, op aanvraag bij het restaurant',
    practice3Title: 'Linnengoed inbegrepen', practice3Text: 'Badjassen, handdoeken en slippers ter beschikking',
    ctaBookSlot: 'TIJDSLOT BOEKEN',
    contactEyebrow: 'CONTACT', contactTitle1: 'Schrijf ons,', contactTitle2: 'of kom langs.',
    addressLabel: 'ADRES', phoneLabel: 'TELEFOON', emailLabel: 'E-MAIL',
    contactHours: 'Onthaal van maandag tot zondag, 9 – 19 uur.', contactHours2: 'Restaurant, gîte en spa: alle aanvragen telefonisch of per e-mail — wij reageren binnen 24 uur.',
    formNameLabel: 'ACHTERNAAM', formFirstNameLabel: 'VOORNAAM', formEmailLabel: 'E-MAIL', formMessageLabel: 'BERICHT',
    formNamePh: 'Uw achternaam', formFirstNamePh: 'Uw voornaam', formEmailPh: 'u@voorbeeld.com', formMessagePh: 'Uw bericht…',
    formSendBtn: 'BERICHT VERSTUREN', formNote: 'Als u op verzenden klikt, wordt uw e-mailprogramma geopend met dit vooraf ingevulde bericht.',
    recruitEyebrow: 'KOM BIJ ONS WERKEN', recruitTitle: 'Vacatures', recruitTagline: 'Le Méandre groeit met de mensen die hier werken.',
    recruitParagraph: 'Wij werven regelmatig personeel voor de keuken, de bediening en het onderhoud van de herberg en de gîte. Niets vrij dat bij u past? Stuur ons een open sollicitatie: wij bewaren elk cv en nemen contact op zodra er een functie vrijkomt.',
    recruitCta: 'MIJN SOLLICITATIE VERSTUREN', recruitEmailNote: 'Cv en motivatiebrief naar:',
    sceneEyebrow: 'PODIUM & KUNST', sceneTitle: 'Le Méandre opent zijn podium', sceneTagline: 'Bent u kunstenaar?',
    sceneParagraph: 'Bent u muzikant, schilder, fotograaf, komiek of podiumkunstenaar? Wilt u exposeren, optreden of een project met ons bedenken? Wij zijn altijd op zoek naar nieuwe werelden en nieuwe gevoeligheden om aan onze gasten te laten ontdekken.',
    sceneFormIntro: 'Stel uw wereld voor', sceneCta: 'MIJN PROJECT VOORSTELLEN',
    sceneDisciplineLabel: 'DISCIPLINE', sceneDisciplinePh: 'Muziek, schilderkunst, fotografie, podiumkunst…',
    sceneProjectLabel: 'UW PROJECT', sceneProjectPh: 'Beschrijf uw wereld, uw project, uw beschikbaarheid…',
    sceneFormNote: 'Als u op verzenden klikt, wordt uw e-mailprogramma geopend met dit vooraf ingevulde bericht.',
    navAgenda: 'AGENDA',
    agendaEyebrow: 'CONCERTEN · MARKTEN · AVONDEN', agendaTitle: 'De Agenda',
    agendaTagline: 'De eerstvolgende afspraken bij Le Méandre: themaavonden, concerten, boerenmarkten en momenten om te delen.',
    agendaEmptyTitle: 'Nog geen data', agendaEmptyText: 'Onze agenda wordt momenteel samengesteld — kom binnenkort terug, of neem contact met ons op om op de hoogte te blijven van komende evenementen.',
    sinceWord: 'SINDS',
    phHero: 'Foto van de herberg — buitenaanzicht, groot formaat', phAccRest: 'Signature gerecht', phAccGites: 'Interieur van de gîte', phAccSpa: 'Spa',
    phRestHero: 'Eetzaal of gerecht — brede banner', phSpaHero: 'Spa — groot immersief formaat', phContact: 'Foto — oprijlaan, poort of toegangsplan',
    phAEmporter: 'Poster van het huidige afhaalaanbod — staand formaat', aemporterCaption: '(niet-contractuele foto)'
  }
};
